// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: KORAD_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_WifiSimbolLabel1;
lv_obj_t * ui_logoLabel1;
lv_obj_t * ui_bodyPanel1;
void ui_event_uLabel1(lv_event_t * e);
lv_obj_t * ui_uLabel1;
void ui_event_iLabel1(lv_event_t * e);
lv_obj_t * ui_iLabel1;
void ui_event_pLabel1(lv_event_t * e);
lv_obj_t * ui_pLabel1;
lv_obj_t * ui_ovpLabel1;
lv_obj_t * ui_cvLabel1;
lv_obj_t * ui_ocpLabel1;
lv_obj_t * ui_ccLabel1;
lv_obj_t * ui_uBar1;
lv_obj_t * ui_iBar1;
lv_obj_t * ui_mLabel1;
lv_obj_t * ui_outLabel1;
void ui_event_wButton1(lv_event_t * e);
lv_obj_t * ui_wButton1;
lv_obj_t * ui_wLabel1;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_WifiSimbolLabel2;
lv_obj_t * ui_logoLabel2;
lv_obj_t * ui_bodyPanel2;
void ui_event_uLabel2(lv_event_t * e);
lv_obj_t * ui_uLabel2;
void ui_event_iLabel2(lv_event_t * e);
lv_obj_t * ui_iLabel2;
lv_obj_t * ui_ovpLabel2;
lv_obj_t * ui_cvLabel2;
lv_obj_t * ui_ocpLabel2;
lv_obj_t * ui_ccLabel2;
lv_obj_t * ui_outLabel2;
lv_obj_t * ui_mLabel2;
lv_obj_t * ui_wnLabel2;
lv_obj_t * ui_rnLabel2;
lv_obj_t * ui_ahnLabel2;
lv_obj_t * ui_awnLabel2;
lv_obj_t * ui_tnLabel2;
lv_obj_t * ui_pLabel2;
lv_obj_t * ui_rLabel2;
lv_obj_t * ui_ahLabel2;
lv_obj_t * ui_whLabel2;
lv_obj_t * ui_tLabel2;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_WifiSimbolLabel3;
lv_obj_t * ui_logoLabel3;
void ui_event_bodyPanel3(lv_event_t * e);
lv_obj_t * ui_bodyPanel3;
void ui_event_uLabel3(lv_event_t * e);
lv_obj_t * ui_uLabel3;
void ui_event_iLabel3(lv_event_t * e);
lv_obj_t * ui_iLabel3;
lv_obj_t * ui_ovpLabel3;
lv_obj_t * ui_cvLabel3;
lv_obj_t * ui_ocpLabel3;
lv_obj_t * ui_ccLabel3;
lv_obj_t * ui_outLabel3;
lv_obj_t * ui_mLabel3;
lv_obj_t * ui_OscVoltLabel;
lv_obj_t * ui_OscAmperLabel;


// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
void ui_event_SettingsScreen(lv_event_t * e);
lv_obj_t * ui_SettingsScreen;
lv_obj_t * ui_WifiMenuPanel;
lv_obj_t * ui_Label1;
void ui_event_WifiMenuSwitch(lv_event_t * e);
lv_obj_t * ui_WifiMenuSwitch;
void ui_event_WifiButton(lv_event_t * e);
lv_obj_t * ui_WifiButton;
void ui_event_WifiIpLabel(lv_event_t * e);
lv_obj_t * ui_WifiIpLabel;
lv_obj_t * ui_EnergyMenuPanel;
lv_obj_t * ui_Label4;
void ui_event_AutoResetSwitch(lv_event_t * e);
lv_obj_t * ui_AutoResetSwitch;
lv_obj_t * ui_ProgMenuPanel;
lv_obj_t * ui_Label3;
void ui_event_UartSwitch(lv_event_t * e);
lv_obj_t * ui_UartSwitch;
void ui_event_BlockUartSwitch(lv_event_t * e);
lv_obj_t * ui_BlockUartSwitch;
lv_obj_t * ui_Label5;
void ui_event_ExteriorMenuPanel(lv_event_t * e);
lv_obj_t * ui_ExteriorMenuPanel;
lv_obj_t * ui_Label7;
void ui_event_ExteriorMenuButton(lv_event_t * e);
lv_obj_t * ui_ExteriorMenuButton;
lv_obj_t * ui_ScreensaverMenuPanel;
lv_obj_t * ui_Label11;
void ui_event_ScreensaverSlider(lv_event_t * e);
lv_obj_t * ui_ScreensaverSlider;
lv_obj_t * ui_ScreensaverLabel;
lv_obj_t * ui_BeeperMenuPanel;
lv_obj_t * ui_BeeperLabel;
lv_obj_t * ui_Label6;
void ui_event_BeeperSlider(lv_event_t * e);
lv_obj_t * ui_BeeperSlider;


// SCREEN: ui_SetScreen
void ui_SetScreen_screen_init(void);
lv_obj_t * ui_SetScreen;
void ui_event_TextAreaUset(lv_event_t * e);
lv_obj_t * ui_TextAreaUset;
void ui_event_TextAreaIset(lv_event_t * e);
lv_obj_t * ui_TextAreaIset;
void ui_event_SetKeyboard(lv_event_t * e);
lv_obj_t * ui_SetKeyboard;
void ui_event_ButtonOk(lv_event_t * e);
lv_obj_t * ui_ButtonOk;
void ui_event_Label9(lv_event_t * e);
lv_obj_t * ui_Label9;
void ui_event_ButtonCancel(lv_event_t * e);
lv_obj_t * ui_ButtonCancel;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label2;


// SCREEN: ui_DebugScreen
void ui_DebugScreen_screen_init(void);
void ui_event_DebugScreen(lv_event_t * e);
lv_obj_t * ui_DebugScreen;
lv_obj_t * ui_WifiSimbolLabel4;
lv_obj_t * ui_uuDebugLabel;
lv_obj_t * ui_iiDebugLabel;
lv_obj_t * ui_uLabel4;
lv_obj_t * ui_iLabel4;
lv_obj_t * ui_Label12;
void ui_event_EdgeDropdown(lv_event_t * e);
lv_obj_t * ui_EdgeDropdown;
void ui_event_DebugSaveButton(lv_event_t * e);
lv_obj_t * ui_DebugSaveButton;
lv_obj_t * ui_Label13;
lv_obj_t * ui_ovpLabel4;
lv_obj_t * ui_cvLabel4;
lv_obj_t * ui_ocpLabel4;
lv_obj_t * ui_ccLabel4;
lv_obj_t * ui_outLabel4;
lv_obj_t * ui_mLabel4;
void ui_event_PrescalerSpinbox(lv_event_t * e);
lv_obj_t * ui_PrescalerSpinbox;
lv_obj_t * ui_Label14;
lv_obj_t * ui_InterErrLabel;
lv_obj_t * ui_ValueErrLabel;
lv_obj_t * ui_ClientsLabel;
void ui_event_ShiftSpinbox(lv_event_t * e);
lv_obj_t * ui_ShiftSpinbox;
void ui_event_ReversCheckbox(lv_event_t * e);
lv_obj_t * ui_ReversCheckbox;
lv_obj_t * ui_Label19;
void ui_event_ShiftPlusButton(lv_event_t * e);
lv_obj_t * ui_ShiftPlusButton;
void ui_event_ShiftMinusButton(lv_event_t * e);
lv_obj_t * ui_ShiftMinusButton;
void ui_event_PrescalerPlusButton(lv_event_t * e);
lv_obj_t * ui_PrescalerPlusButton;
void ui_event_PrescalerMinusButton(lv_event_t * e);
lv_obj_t * ui_PrescalerMinusButton;


// SCREEN: ui_WifiScreen
void ui_WifiScreen_screen_init(void);
void ui_event_WifiScreen(lv_event_t * e);
lv_obj_t * ui_WifiScreen;
lv_obj_t * ui_WifiStatusLabel;
void ui_event_WifiCloseButton(lv_event_t * e);
lv_obj_t * ui_WifiCloseButton;
lv_obj_t * ui_WifiSsidNameLabel;


// SCREEN: ui_PasswordScreen
void ui_PasswordScreen_screen_init(void);
lv_obj_t * ui_PasswordScreen;
void ui_event_PasswordConnectButton(lv_event_t * e);
lv_obj_t * ui_PasswordConnectButton;
lv_obj_t * ui_Label15;
lv_obj_t * ui_PasswordLabel;
void ui_event_PasswordTextArea(lv_event_t * e);
lv_obj_t * ui_PasswordTextArea;
void ui_event_PasswordCloseButton(lv_event_t * e);
lv_obj_t * ui_PasswordCloseButton;
void ui_event_PasswordKeyboard(lv_event_t * e);
lv_obj_t * ui_PasswordKeyboard;


// SCREEN: ui_ExteriorScreen
void ui_ExteriorScreen_screen_init(void);
lv_obj_t * ui_ExteriorScreen;
lv_obj_t * ui_ExamplePanel;
void ui_event_Colorwheel(lv_event_t * e);
lv_obj_t * ui_Colorwheel;
void ui_event_ColorDropdown(lv_event_t * e);
lv_obj_t * ui_ColorDropdown;
lv_obj_t * ui_ExampleLabel;
void ui_event_ExteriorCloseButton(lv_event_t * e);
lv_obj_t * ui_ExteriorCloseButton;
void ui_event_DefaultButton(lv_event_t * e);
lv_obj_t * ui_DefaultButton;
lv_obj_t * ui_Label17;
void ui_event_FontDropdown(lv_event_t * e);
lv_obj_t * ui_FontDropdown;
void ui_event_BackgroundSlider(lv_event_t * e);
lv_obj_t * ui_BackgroundSlider;
void ui_event_BrightnesSlider(lv_event_t * e);
lv_obj_t * ui_BrightnesSlider;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label18;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Screen1LoadStartEvent_cb(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_SettingsScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_DebugScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_DebugScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_uLabel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        uLabelClickEvent_cb(e);
    }
}
void ui_event_iLabel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        iLabelClickEvent_cb(e);
    }
}
void ui_event_pLabel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        wButtonClickEvent_cb(e);
    }
}
void ui_event_wButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        wButtonClickEvent_cb(e);
    }
}
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Screen2LoadStartEvent_cb(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_SettingsScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_DebugScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_DebugScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_uLabel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        uLabelClickEvent_cb(e);
    }
}
void ui_event_iLabel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        iLabelClickEvent_cb(e);
    }
}
void ui_event_Screen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Screen3LoadStartEvent_cb(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_SettingsScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_DebugScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_DebugScreen_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Screen3LoadedEvent_cb(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        Screen3UnloadStartEvent(e);
    }
}
void ui_event_bodyPanel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OscillPanelClickEvent_cb(e);
    }
}
void ui_event_uLabel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        uLabelClickEvent_cb(e);
    }
}
void ui_event_iLabel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        iLabelClickEvent_cb(e);
    }
}
void ui_event_SettingsScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        SettingsScreenGestureUpDownEvent_cb(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        SettingsScreenLoadStartEvent_cb(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        SettingsScreenGestureUpDownEvent_cb(e);
    }
}
void ui_event_WifiMenuSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        WifiMenuSwitchEvent_cb(e);
    }
}
void ui_event_WifiButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        WifiButtonClickEvent_cb(e);
    }
}
void ui_event_WifiIpLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        WifiButtonClickEvent_cb(e);
    }
}
void ui_event_AutoResetSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        JustDoBeepEvent_cb(e);
    }
}
void ui_event_UartSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        UartSwitchClicedEvent_cb(e);
    }
}
void ui_event_BlockUartSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        JustDoBeepEvent_cb(e);
    }
}
void ui_event_ExteriorMenuPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ExteriorMenuButtonClickEvent_cb(e);
    }
}
void ui_event_ExteriorMenuButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ExteriorMenuButtonClickEvent_cb(e);
    }
}
void ui_event_ScreensaverSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ScreensaverSliderEvent_cb(e);
    }
}
void ui_event_BeeperSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        BeeperSliderEvent_cb(e);
    }
}
void ui_event_TextAreaUset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        UsetEvent_cb(e);
    }
}
void ui_event_TextAreaIset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        IsetEvent_cb(e);
    }
}
void ui_event_SetKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        JustDoBeepEvent_cb(e);
    }
}
void ui_event_ButtonOk(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OkButtonEvent_cb(e);
    }
}
void ui_event_Label9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OkButtonEvent_cb(e);
    }
}
void ui_event_ButtonCancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        CancelButtonEvent_cb(e);
    }
}
void ui_event_DebugScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        DebugScreenLoadStartEvent_cb(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        DebugScreenGesureUpDownEvent_cb(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        DebugScreenGesureUpDownEvent_cb(e);
    }
}
void ui_event_EdgeDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        EdgeDropdownEvent_cb(e);
    }
}
void ui_event_DebugSaveButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        SaveButtonClickEvent_cb(e);
    }
}
void ui_event_PrescalerSpinbox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        PrescalerSpinboxValueChangedEvent_cb(e);
    }
}
void ui_event_ShiftSpinbox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ShiftSpinboxEvent_cb(e);
    }
}
void ui_event_ReversCheckbox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ReversCheckboxEvent_cb(e);
    }
}
void ui_event_ShiftPlusButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_ShiftSpinbox, 1);
    }
}
void ui_event_ShiftMinusButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_ShiftSpinbox, -1);
    }
}
void ui_event_PrescalerPlusButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_PrescalerSpinbox, 1);
    }
}
void ui_event_PrescalerMinusButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_PrescalerSpinbox, -1);
    }
}
void ui_event_WifiScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        WifiScreenLoadStartEvent_cb(e);
    }
}
void ui_event_WifiCloseButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        WifiCloseButton_cb(e);
    }
}
void ui_event_PasswordConnectButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        PasswordConnectButton_cb(e);
    }
}
void ui_event_PasswordTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        PasswordTextAreaFocusedEvent_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        PasswordKeyboardReadyEvent_cb(e);
    }
}
void ui_event_PasswordCloseButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        PasswordCloseButton_cb(e);
    }
}
void ui_event_PasswordKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        PasswordKeyboardReadyEvent_cb(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        JustDoBeepEvent_cb(e);
    }
}
void ui_event_Colorwheel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ColorwheelEvent_cb(e);
    }
}
void ui_event_ColorDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ColorDropdownEvent_cb(e);
    }
}
void ui_event_ExteriorCloseButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ExteriorCloseButton_cb(e);
    }
}
void ui_event_DefaultButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        DefaultButtonClickEvent_cb(e);
    }
}
void ui_event_FontDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        FontDropdownEvent_cb(e);
    }
}
void ui_event_BackgroundSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        BackgroundSliderEvent_cb(e);
    }
}
void ui_event_BrightnesSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        BrightnesSliderEvent_cb(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_SettingsScreen_screen_init();
    ui_SetScreen_screen_init();
    ui_DebugScreen_screen_init();
    ui_WifiScreen_screen_init();
    ui_PasswordScreen_screen_init();
    ui_ExteriorScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
