// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: KORAD_Project

#ifndef _KORAD_PROJECT_UI_H
#define _KORAD_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_WifiSimbolLabel1;
extern lv_obj_t * ui_logoLabel1;
extern lv_obj_t * ui_bodyPanel1;
void ui_event_uLabel1(lv_event_t * e);
extern lv_obj_t * ui_uLabel1;
void ui_event_iLabel1(lv_event_t * e);
extern lv_obj_t * ui_iLabel1;
void ui_event_pLabel1(lv_event_t * e);
extern lv_obj_t * ui_pLabel1;
extern lv_obj_t * ui_ovpLabel1;
extern lv_obj_t * ui_cvLabel1;
extern lv_obj_t * ui_ocpLabel1;
extern lv_obj_t * ui_ccLabel1;
extern lv_obj_t * ui_uBar1;
extern lv_obj_t * ui_iBar1;
extern lv_obj_t * ui_mLabel1;
extern lv_obj_t * ui_outLabel1;
void ui_event_wButton1(lv_event_t * e);
extern lv_obj_t * ui_wButton1;
extern lv_obj_t * ui_wLabel1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_WifiSimbolLabel2;
extern lv_obj_t * ui_logoLabel2;
extern lv_obj_t * ui_bodyPanel2;
void ui_event_uLabel2(lv_event_t * e);
extern lv_obj_t * ui_uLabel2;
void ui_event_iLabel2(lv_event_t * e);
extern lv_obj_t * ui_iLabel2;
extern lv_obj_t * ui_ovpLabel2;
extern lv_obj_t * ui_cvLabel2;
extern lv_obj_t * ui_ocpLabel2;
extern lv_obj_t * ui_ccLabel2;
extern lv_obj_t * ui_outLabel2;
extern lv_obj_t * ui_mLabel2;
extern lv_obj_t * ui_wnLabel2;
extern lv_obj_t * ui_rnLabel2;
extern lv_obj_t * ui_ahnLabel2;
extern lv_obj_t * ui_awnLabel2;
extern lv_obj_t * ui_tnLabel2;
extern lv_obj_t * ui_pLabel2;
extern lv_obj_t * ui_rLabel2;
extern lv_obj_t * ui_ahLabel2;
extern lv_obj_t * ui_whLabel2;
extern lv_obj_t * ui_tLabel2;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_WifiSimbolLabel3;
extern lv_obj_t * ui_logoLabel3;
void ui_event_bodyPanel3(lv_event_t * e);
extern lv_obj_t * ui_bodyPanel3;
void ui_event_uLabel3(lv_event_t * e);
extern lv_obj_t * ui_uLabel3;
void ui_event_iLabel3(lv_event_t * e);
extern lv_obj_t * ui_iLabel3;
extern lv_obj_t * ui_ovpLabel3;
extern lv_obj_t * ui_cvLabel3;
extern lv_obj_t * ui_ocpLabel3;
extern lv_obj_t * ui_ccLabel3;
extern lv_obj_t * ui_outLabel3;
extern lv_obj_t * ui_mLabel3;
extern lv_obj_t * ui_OscVoltLabel;
extern lv_obj_t * ui_OscAmperLabel;
// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
void ui_event_SettingsScreen(lv_event_t * e);
extern lv_obj_t * ui_SettingsScreen;
extern lv_obj_t * ui_WifiMenuPanel;
extern lv_obj_t * ui_Label1;
void ui_event_WifiMenuSwitch(lv_event_t * e);
extern lv_obj_t * ui_WifiMenuSwitch;
void ui_event_WifiButton(lv_event_t * e);
extern lv_obj_t * ui_WifiButton;
void ui_event_WifiIpLabel(lv_event_t * e);
extern lv_obj_t * ui_WifiIpLabel;
extern lv_obj_t * ui_EnergyMenuPanel;
extern lv_obj_t * ui_Label4;
void ui_event_AutoResetSwitch(lv_event_t * e);
extern lv_obj_t * ui_AutoResetSwitch;
extern lv_obj_t * ui_ProgMenuPanel;
extern lv_obj_t * ui_Label3;
void ui_event_UartSwitch(lv_event_t * e);
extern lv_obj_t * ui_UartSwitch;
void ui_event_BlockUartSwitch(lv_event_t * e);
extern lv_obj_t * ui_BlockUartSwitch;
extern lv_obj_t * ui_Label5;
void ui_event_ExteriorMenuPanel(lv_event_t * e);
extern lv_obj_t * ui_ExteriorMenuPanel;
extern lv_obj_t * ui_Label7;
void ui_event_ExteriorMenuButton(lv_event_t * e);
extern lv_obj_t * ui_ExteriorMenuButton;
extern lv_obj_t * ui_ScreensaverMenuPanel;
extern lv_obj_t * ui_Label11;
void ui_event_ScreensaverSlider(lv_event_t * e);
extern lv_obj_t * ui_ScreensaverSlider;
extern lv_obj_t * ui_ScreensaverLabel;
extern lv_obj_t * ui_BeeperMenuPanel;
extern lv_obj_t * ui_BeeperLabel;
extern lv_obj_t * ui_Label6;
void ui_event_BeeperSlider(lv_event_t * e);
extern lv_obj_t * ui_BeeperSlider;
// SCREEN: ui_SetScreen
void ui_SetScreen_screen_init(void);
extern lv_obj_t * ui_SetScreen;
void ui_event_TextAreaUset(lv_event_t * e);
extern lv_obj_t * ui_TextAreaUset;
void ui_event_TextAreaIset(lv_event_t * e);
extern lv_obj_t * ui_TextAreaIset;
void ui_event_SetKeyboard(lv_event_t * e);
extern lv_obj_t * ui_SetKeyboard;
void ui_event_ButtonOk(lv_event_t * e);
extern lv_obj_t * ui_ButtonOk;
void ui_event_Label9(lv_event_t * e);
extern lv_obj_t * ui_Label9;
void ui_event_ButtonCancel(lv_event_t * e);
extern lv_obj_t * ui_ButtonCancel;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_DebugScreen
void ui_DebugScreen_screen_init(void);
void ui_event_DebugScreen(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen;
extern lv_obj_t * ui_WifiSimbolLabel4;
extern lv_obj_t * ui_uuDebugLabel;
extern lv_obj_t * ui_iiDebugLabel;
extern lv_obj_t * ui_uLabel4;
extern lv_obj_t * ui_iLabel4;
extern lv_obj_t * ui_Label12;
void ui_event_EdgeDropdown(lv_event_t * e);
extern lv_obj_t * ui_EdgeDropdown;
void ui_event_DebugSaveButton(lv_event_t * e);
extern lv_obj_t * ui_DebugSaveButton;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_ovpLabel4;
extern lv_obj_t * ui_cvLabel4;
extern lv_obj_t * ui_ocpLabel4;
extern lv_obj_t * ui_ccLabel4;
extern lv_obj_t * ui_outLabel4;
extern lv_obj_t * ui_mLabel4;
void ui_event_PrescalerSpinbox(lv_event_t * e);
extern lv_obj_t * ui_PrescalerSpinbox;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_InterErrLabel;
extern lv_obj_t * ui_ValueErrLabel;
extern lv_obj_t * ui_ClientsLabel;
void ui_event_ShiftSpinbox(lv_event_t * e);
extern lv_obj_t * ui_ShiftSpinbox;
void ui_event_ReversCheckbox(lv_event_t * e);
extern lv_obj_t * ui_ReversCheckbox;
extern lv_obj_t * ui_Label19;
void ui_event_ShiftPlusButton(lv_event_t * e);
extern lv_obj_t * ui_ShiftPlusButton;
void ui_event_ShiftMinusButton(lv_event_t * e);
extern lv_obj_t * ui_ShiftMinusButton;
void ui_event_PrescalerPlusButton(lv_event_t * e);
extern lv_obj_t * ui_PrescalerPlusButton;
void ui_event_PrescalerMinusButton(lv_event_t * e);
extern lv_obj_t * ui_PrescalerMinusButton;
// SCREEN: ui_WifiScreen
void ui_WifiScreen_screen_init(void);
void ui_event_WifiScreen(lv_event_t * e);
extern lv_obj_t * ui_WifiScreen;
extern lv_obj_t * ui_WifiStatusLabel;
void ui_event_WifiCloseButton(lv_event_t * e);
extern lv_obj_t * ui_WifiCloseButton;
extern lv_obj_t * ui_WifiSsidNameLabel;
// SCREEN: ui_PasswordScreen
void ui_PasswordScreen_screen_init(void);
extern lv_obj_t * ui_PasswordScreen;
void ui_event_PasswordConnectButton(lv_event_t * e);
extern lv_obj_t * ui_PasswordConnectButton;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_PasswordLabel;
void ui_event_PasswordTextArea(lv_event_t * e);
extern lv_obj_t * ui_PasswordTextArea;
void ui_event_PasswordCloseButton(lv_event_t * e);
extern lv_obj_t * ui_PasswordCloseButton;
void ui_event_PasswordKeyboard(lv_event_t * e);
extern lv_obj_t * ui_PasswordKeyboard;
// SCREEN: ui_ExteriorScreen
void ui_ExteriorScreen_screen_init(void);
extern lv_obj_t * ui_ExteriorScreen;
extern lv_obj_t * ui_ExamplePanel;
void ui_event_Colorwheel(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel;
void ui_event_ColorDropdown(lv_event_t * e);
extern lv_obj_t * ui_ColorDropdown;
extern lv_obj_t * ui_ExampleLabel;
void ui_event_ExteriorCloseButton(lv_event_t * e);
extern lv_obj_t * ui_ExteriorCloseButton;
void ui_event_DefaultButton(lv_event_t * e);
extern lv_obj_t * ui_DefaultButton;
extern lv_obj_t * ui_Label17;
void ui_event_FontDropdown(lv_event_t * e);
extern lv_obj_t * ui_FontDropdown;
void ui_event_BackgroundSlider(lv_event_t * e);
extern lv_obj_t * ui_BackgroundSlider;
void ui_event_BrightnesSlider(lv_event_t * e);
extern lv_obj_t * ui_BrightnesSlider;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_indicator_ver_back_png);    // assets\indicator_ver_back.png
LV_IMG_DECLARE(ui_img_indicator_ver_front_png);    // assets\indicator_ver_front.png

LV_FONT_DECLARE(ui_font_Electro38);
LV_FONT_DECLARE(ui_font_Electro78);
LV_FONT_DECLARE(ui_font_Roboto38);
LV_FONT_DECLARE(ui_font_Roboto78);
LV_FONT_DECLARE(ui_font_Segment38);
LV_FONT_DECLARE(ui_font_Segment78);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
