// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: KORAD_Project

#include "ui.h"

#include <math.h>

void ui_DebugScreen_screen_init(void)
{
    ui_DebugScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DebugScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiSimbolLabel4 = lv_label_create(ui_DebugScreen);
    lv_obj_set_width(ui_WifiSimbolLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiSimbolLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiSimbolLabel4, 4);
    lv_obj_set_y(ui_WifiSimbolLabel4, 2);
    lv_label_set_text(ui_WifiSimbolLabel4, "W");
    lv_obj_set_style_text_color(ui_WifiSimbolLabel4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiSimbolLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uuDebugLabel = lv_label_create(ui_DebugScreen);
    lv_obj_set_width(ui_uuDebugLabel, lv_pct(49));
    lv_obj_set_height(ui_uuDebugLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uuDebugLabel, 20);
    lv_obj_set_y(ui_uuDebugLabel, -52);
    lv_obj_set_align(ui_uuDebugLabel, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_uuDebugLabel, "uuLabel");
    lv_obj_set_style_text_font(ui_uuDebugLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iiDebugLabel = lv_label_create(ui_DebugScreen);
    lv_obj_set_width(ui_iiDebugLabel, lv_pct(50));
    lv_obj_set_height(ui_iiDebugLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iiDebugLabel, 20);
    lv_obj_set_y(ui_iiDebugLabel, -19);
    lv_obj_set_align(ui_iiDebugLabel, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_iiDebugLabel, "iiLabel");
    lv_obj_set_style_text_font(ui_iiDebugLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uLabel4 = lv_label_create(ui_DebugScreen);
    lv_obj_set_width(ui_uLabel4, 150);
    lv_obj_set_height(ui_uLabel4, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_uLabel4, -19);
    lv_obj_set_y(ui_uLabel4, 30);
    lv_obj_set_align(ui_uLabel4, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_uLabel4, "88.88");
    lv_obj_set_style_text_letter_space(ui_uLabel4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_uLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_uLabel4, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uLabel4, &ui_font_Segment38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iLabel4 = lv_label_create(ui_DebugScreen);
    lv_obj_set_width(ui_iLabel4, 150);
    lv_obj_set_height(ui_iLabel4, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_iLabel4, -19);
    lv_obj_set_y(ui_iLabel4, 77);
    lv_obj_set_align(ui_iLabel4, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_iLabel4, "88.88");
    lv_obj_set_style_text_letter_space(ui_iLabel4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_iLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_iLabel4, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iLabel4, &ui_font_Segment38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_DebugScreen);
    lv_obj_set_height(ui_Label12, 15);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label12, 31);
    lv_obj_set_y(ui_Label12, 2);
    lv_label_set_text(ui_Label12, "DEBUG");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xA5FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EdgeDropdown = lv_dropdown_create(ui_DebugScreen);
    lv_dropdown_set_options(ui_EdgeDropdown, "Before edge\nAfter edge");
    lv_obj_set_width(ui_EdgeDropdown, 173);
    lv_obj_set_height(ui_EdgeDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EdgeDropdown, 20);
    lv_obj_set_y(ui_EdgeDropdown, 115);
    lv_obj_add_flag(ui_EdgeDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_DebugSaveButton = lv_btn_create(ui_DebugScreen);
    lv_obj_set_width(ui_DebugSaveButton, 100);
    lv_obj_set_height(ui_DebugSaveButton, 50);
    lv_obj_set_x(ui_DebugSaveButton, 142);
    lv_obj_set_y(ui_DebugSaveButton, 111);
    lv_obj_set_align(ui_DebugSaveButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DebugSaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DebugSaveButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DebugSaveButton, lv_color_hex(0x7689AC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DebugSaveButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_DebugSaveButton, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_DebugSaveButton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DebugSaveButton, lv_color_hex(0x28DCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DebugSaveButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DebugSaveButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_DebugSaveButton);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Save");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ovpLabel4 = lv_label_create(ui_DebugScreen);
    lv_obj_set_width(ui_ovpLabel4, 60);
    lv_obj_set_height(ui_ovpLabel4, 28);
    lv_obj_set_x(ui_ovpLabel4, 222);
    lv_obj_set_y(ui_ovpLabel4, 32);
    lv_label_set_text(ui_ovpLabel4, "OVP");
    lv_obj_set_style_text_color(ui_ovpLabel4, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ovpLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ovpLabel4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ovpLabel4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ovpLabel4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ovpLabel4, lv_color_hex(0x7C7C7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ovpLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ovpLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ovpLabel4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ovpLabel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ovpLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cvLabel4 = lv_label_create(ui_DebugScreen);
    lv_obj_set_width(ui_cvLabel4, 60);
    lv_obj_set_height(ui_cvLabel4, 28);
    lv_obj_set_x(ui_cvLabel4, 222);
    lv_obj_set_y(ui_cvLabel4, 68);
    lv_label_set_text(ui_cvLabel4, "CV");
    lv_obj_set_style_text_color(ui_cvLabel4, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cvLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cvLabel4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cvLabel4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cvLabel4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cvLabel4, lv_color_hex(0x7C7C7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cvLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cvLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cvLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cvLabel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cvLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ocpLabel4 = lv_label_create(ui_DebugScreen);
    lv_obj_set_width(ui_ocpLabel4, 60);
    lv_obj_set_height(ui_ocpLabel4, 28);
    lv_obj_set_x(ui_ocpLabel4, 222);
    lv_obj_set_y(ui_ocpLabel4, 141);
    lv_label_set_text(ui_ocpLabel4, "OCP");
    lv_obj_set_style_text_color(ui_ocpLabel4, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ocpLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ocpLabel4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ocpLabel4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ocpLabel4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ocpLabel4, lv_color_hex(0x7C7C7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ocpLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ocpLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ocpLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ocpLabel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ocpLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ccLabel4 = lv_label_create(ui_DebugScreen);
    lv_obj_set_width(ui_ccLabel4, 60);
    lv_obj_set_height(ui_ccLabel4, 28);
    lv_obj_set_x(ui_ccLabel4, 222);
    lv_obj_set_y(ui_ccLabel4, 104);
    lv_label_set_text(ui_ccLabel4, "CC");
    lv_obj_set_style_text_color(ui_ccLabel4, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ccLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ccLabel4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ccLabel4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ccLabel4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ccLabel4, lv_color_hex(0x7C7C7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ccLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ccLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ccLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ccLabel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ccLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outLabel4 = lv_label_create(ui_DebugScreen);
    lv_obj_set_width(ui_outLabel4, 60);
    lv_obj_set_height(ui_outLabel4, 28);
    lv_obj_set_x(ui_outLabel4, 222);
    lv_obj_set_y(ui_outLabel4, 214);
    lv_label_set_text(ui_outLabel4, "OFF");
    lv_obj_set_style_text_color(ui_outLabel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_outLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_outLabel4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_outLabel4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_outLabel4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_outLabel4, lv_color_hex(0x11A51D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_outLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_outLabel4, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_outLabel4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_outLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_outLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_outLabel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_outLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mLabel4 = lv_label_create(ui_DebugScreen);
    lv_obj_set_width(ui_mLabel4, 60);
    lv_obj_set_height(ui_mLabel4, 28);
    lv_obj_set_x(ui_mLabel4, 222);
    lv_obj_set_y(ui_mLabel4, 177);
    lv_label_set_text(ui_mLabel4, "MO");
    lv_obj_set_style_text_color(ui_mLabel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_mLabel4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mLabel4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_mLabel4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mLabel4, lv_color_hex(0x4411A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_mLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_mLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_mLabel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_mLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrescalerSpinbox = lv_spinbox_create(ui_DebugScreen);
    lv_obj_set_width(ui_PrescalerSpinbox, 54);
    lv_obj_set_height(ui_PrescalerSpinbox, 45);
    lv_obj_set_x(ui_PrescalerSpinbox, 143);
    lv_obj_set_y(ui_PrescalerSpinbox, 28);
    lv_obj_set_align(ui_PrescalerSpinbox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PrescalerSpinbox, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_spinbox_set_digit_format(ui_PrescalerSpinbox, 2, 0);
    lv_spinbox_set_range(ui_PrescalerSpinbox, 2, 20);
    lv_spinbox_set_step(ui_PrescalerSpinbox, round(pow(10, 1 - 1)));
    lv_spinbox_set_value(ui_PrescalerSpinbox, 5);
    lv_obj_set_style_text_font(ui_PrescalerSpinbox, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PrescalerSpinbox, lv_color_hex(0x222222), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrescalerSpinbox, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_DebugScreen);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -65);
    lv_obj_set_y(ui_Label14, -12);
    lv_obj_set_align(ui_Label14, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label14, "Prescaler");

    ui_InterErrLabel = lv_label_create(ui_DebugScreen);
    lv_obj_set_width(ui_InterErrLabel, 114);
    lv_obj_set_height(ui_InterErrLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InterErrLabel, 38);
    lv_obj_set_y(ui_InterErrLabel, 2);
    lv_obj_set_align(ui_InterErrLabel, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_InterErrLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_InterErrLabel, "Timeouts");
    lv_obj_set_style_text_align(ui_InterErrLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueErrLabel = lv_label_create(ui_DebugScreen);
    lv_obj_set_width(ui_ValueErrLabel, 97);
    lv_obj_set_height(ui_ValueErrLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValueErrLabel, 168);
    lv_obj_set_y(ui_ValueErrLabel, 2);
    lv_obj_set_align(ui_ValueErrLabel, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_ValueErrLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_ValueErrLabel, "Errors");
    lv_obj_set_style_text_align(ui_ValueErrLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClientsLabel = lv_label_create(ui_DebugScreen);
    lv_obj_set_width(ui_ClientsLabel, 105);
    lv_obj_set_height(ui_ClientsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClientsLabel, -91);
    lv_obj_set_y(ui_ClientsLabel, 2);
    lv_obj_set_align(ui_ClientsLabel, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_ClientsLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_ClientsLabel, "Wifi Clients");
    lv_obj_set_style_text_align(ui_ClientsLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShiftSpinbox = lv_spinbox_create(ui_DebugScreen);
    lv_obj_set_width(ui_ShiftSpinbox, 45);
    lv_obj_set_height(ui_ShiftSpinbox, 45);
    lv_obj_set_x(ui_ShiftSpinbox, -138);
    lv_obj_set_y(ui_ShiftSpinbox, -90);
    lv_obj_set_align(ui_ShiftSpinbox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ShiftSpinbox, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_spinbox_set_digit_format(ui_ShiftSpinbox, 1, 0);
    lv_spinbox_set_range(ui_ShiftSpinbox, 0, 4);
    lv_spinbox_set_step(ui_ShiftSpinbox, round(pow(10, 1 - 1)));
    lv_spinbox_set_value(ui_ShiftSpinbox, 1);
    lv_obj_set_style_text_align(ui_ShiftSpinbox, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ShiftSpinbox, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ShiftSpinbox, lv_color_hex(0x222222), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShiftSpinbox, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_ReversCheckbox = lv_checkbox_create(ui_DebugScreen);
    lv_checkbox_set_text(ui_ReversCheckbox, "Revers");
    lv_obj_set_width(ui_ReversCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReversCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReversCheckbox, -135);
    lv_obj_set_y(ui_ReversCheckbox, 32);
    lv_obj_set_align(ui_ReversCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ReversCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label19 = lv_label_create(ui_DebugScreen);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 85);
    lv_obj_set_y(ui_Label19, -124);
    lv_obj_set_align(ui_Label19, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label19, "Shift");

    ui_ShiftPlusButton = lv_btn_create(ui_DebugScreen);
    lv_obj_set_width(ui_ShiftPlusButton, 45);
    lv_obj_set_height(ui_ShiftPlusButton, 45);
    lv_obj_set_x(ui_ShiftPlusButton, -90);
    lv_obj_set_y(ui_ShiftPlusButton, -90);
    lv_obj_set_align(ui_ShiftPlusButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ShiftPlusButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ShiftPlusButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ShiftPlusButton, lv_color_hex(0x7689AC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShiftPlusButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ShiftPlusButton, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ShiftPlusButton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ShiftPlusButton, lv_color_hex(0x28DCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ShiftPlusButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ShiftPlusButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ShiftPlusButton, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShiftMinusButton = lv_btn_create(ui_DebugScreen);
    lv_obj_set_width(ui_ShiftMinusButton, 45);
    lv_obj_set_height(ui_ShiftMinusButton, 45);
    lv_obj_set_x(ui_ShiftMinusButton, -187);
    lv_obj_set_y(ui_ShiftMinusButton, -90);
    lv_obj_set_align(ui_ShiftMinusButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ShiftMinusButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ShiftMinusButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ShiftMinusButton, lv_color_hex(0x7689AC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShiftMinusButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ShiftMinusButton, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ShiftMinusButton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ShiftMinusButton, lv_color_hex(0x28DCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ShiftMinusButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ShiftMinusButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ShiftMinusButton, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrescalerPlusButton = lv_btn_create(ui_DebugScreen);
    lv_obj_set_width(ui_PrescalerPlusButton, 45);
    lv_obj_set_height(ui_PrescalerPlusButton, 45);
    lv_obj_set_x(ui_PrescalerPlusButton, 195);
    lv_obj_set_y(ui_PrescalerPlusButton, 28);
    lv_obj_set_align(ui_PrescalerPlusButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrescalerPlusButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrescalerPlusButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PrescalerPlusButton, lv_color_hex(0x7689AC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrescalerPlusButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PrescalerPlusButton, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PrescalerPlusButton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PrescalerPlusButton, lv_color_hex(0x28DCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PrescalerPlusButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PrescalerPlusButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrescalerPlusButton, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrescalerMinusButton = lv_btn_create(ui_DebugScreen);
    lv_obj_set_width(ui_PrescalerMinusButton, 45);
    lv_obj_set_height(ui_PrescalerMinusButton, 45);
    lv_obj_set_x(ui_PrescalerMinusButton, 90);
    lv_obj_set_y(ui_PrescalerMinusButton, 28);
    lv_obj_set_align(ui_PrescalerMinusButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrescalerMinusButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrescalerMinusButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PrescalerMinusButton, lv_color_hex(0x7689AC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrescalerMinusButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PrescalerMinusButton, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PrescalerMinusButton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PrescalerMinusButton, lv_color_hex(0x28DCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PrescalerMinusButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PrescalerMinusButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrescalerMinusButton, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_EdgeDropdown, ui_event_EdgeDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugSaveButton, ui_event_DebugSaveButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrescalerSpinbox, ui_event_PrescalerSpinbox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ShiftSpinbox, ui_event_ShiftSpinbox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ReversCheckbox, ui_event_ReversCheckbox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ShiftPlusButton, ui_event_ShiftPlusButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ShiftMinusButton, ui_event_ShiftMinusButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrescalerPlusButton, ui_event_PrescalerPlusButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrescalerMinusButton, ui_event_PrescalerMinusButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DebugScreen, ui_event_DebugScreen, LV_EVENT_ALL, NULL);

}
