// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: KORAD_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Screen1LoadStartEvent_cb(lv_event_t * e);
void uLabelClickEvent_cb(lv_event_t * e);
void iLabelClickEvent_cb(lv_event_t * e);
void wButtonClickEvent_cb(lv_event_t * e);
void Screen2LoadStartEvent_cb(lv_event_t * e);
void Screen3LoadStartEvent_cb(lv_event_t * e);
void Screen3LoadedEvent_cb(lv_event_t * e);
void Screen3UnloadStartEvent(lv_event_t * e);
void OscillPanelClickEvent_cb(lv_event_t * e);
void SettingsScreenGestureUpDownEvent_cb(lv_event_t * e);
void SettingsScreenLoadStartEvent_cb(lv_event_t * e);
void WifiMenuSwitchEvent_cb(lv_event_t * e);
void WifiButtonClickEvent_cb(lv_event_t * e);
void JustDoBeepEvent_cb(lv_event_t * e);
void UartSwitchClicedEvent_cb(lv_event_t * e);
void ExteriorMenuButtonClickEvent_cb(lv_event_t * e);
void ScreensaverSliderEvent_cb(lv_event_t * e);
void BeeperSliderEvent_cb(lv_event_t * e);
void UsetEvent_cb(lv_event_t * e);
void IsetEvent_cb(lv_event_t * e);
void OkButtonEvent_cb(lv_event_t * e);
void CancelButtonEvent_cb(lv_event_t * e);
void DebugScreenLoadStartEvent_cb(lv_event_t * e);
void DebugScreenGesureUpDownEvent_cb(lv_event_t * e);
void EdgeDropdownEvent_cb(lv_event_t * e);
void SaveButtonClickEvent_cb(lv_event_t * e);
void PrescalerSpinboxValueChangedEvent_cb(lv_event_t * e);
void ShiftSpinboxEvent_cb(lv_event_t * e);
void ReversCheckboxEvent_cb(lv_event_t * e);
void WifiScreenLoadStartEvent_cb(lv_event_t * e);
void WifiCloseButton_cb(lv_event_t * e);
void PasswordConnectButton_cb(lv_event_t * e);
void PasswordTextAreaFocusedEvent_cb(lv_event_t * e);
void PasswordKeyboardReadyEvent_cb(lv_event_t * e);
void PasswordCloseButton_cb(lv_event_t * e);
void ColorwheelEvent_cb(lv_event_t * e);
void ColorDropdownEvent_cb(lv_event_t * e);
void ExteriorCloseButton_cb(lv_event_t * e);
void DefaultButtonClickEvent_cb(lv_event_t * e);
void FontDropdownEvent_cb(lv_event_t * e);
void BackgroundSliderEvent_cb(lv_event_t * e);
void BrightnesSliderEvent_cb(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
