// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: KORAD_Project

#include "ui.h"
#include "common.h"
#include "korad.h"
#include "oscill.h"

lv_obj_t * prevScreen;
lv_timer_t * wifiTimer;

bool setVoltage;
uint16_t locUset = 0;
uint16_t locIset = 0;
static bool showWatt = true;
persistent_data_t locPersistData;

/*Create a keyboard map*/
const char * kb_map[] = {"1", "2", "3", "\n",
						"4", "5", "6", "\n",
						"7", "8", "9", "\n",
						LV_SYMBOL_BACKSPACE,  "0", ".", NULL };

/*Set the relative width of the buttons and other controls*/
const lv_btnmatrix_ctrl_t kb_ctrl[] = { 4, 4, 4,
										4, 4, 4,
										4, 4, 4,
										4, 4, 4};

fontSet_t fontsArray[3] = {{&ui_font_Segment78, &ui_font_Segment38},
							{&ui_font_Electro78, &ui_font_Electro38},
							{&ui_font_Roboto78, &ui_font_Roboto38}};

//===============================================================================================
static void PrescalerSpinbox_increment_event_cb(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_SHORT_CLICKED || code  == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_increment(ui_PrescalerSpinbox);
    }
}
//===============================================================================================

static void PrescalerSpinbox_decrement_event_cb(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_decrement(ui_PrescalerSpinbox);
    }
}
//===============================================================================================
static void ShiftSpinbox_increment_event_cb(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_SHORT_CLICKED || code  == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_increment(ui_ShiftSpinbox);
    }
}
//===============================================================================================

static void ShiftSpinbox_decrement_event_cb(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_SHORT_CLICKED || code == LV_EVENT_LONG_PRESSED_REPEAT) {
        lv_spinbox_decrement(ui_ShiftSpinbox);
    }
}
//===============================================================================================
void ApplyBackgroundColors(void)
{
  	lv_obj_set_style_bg_color(ui_ExamplePanel, bgColorsArray[gPersistData.bgColorIdx], LV_PART_MAIN);
  	lv_obj_set_style_bg_color(ui_bodyPanel1, bgColorsArray[gPersistData.bgColorIdx], LV_PART_MAIN);
  	lv_obj_set_style_bg_color(ui_bodyPanel2, bgColorsArray[gPersistData.bgColorIdx], LV_PART_MAIN);  	
  	lv_obj_set_style_bg_color(ui_bodyPanel3, bgColorsArray[gPersistData.bgColorIdx], LV_PART_MAIN);  	
}
//===================================================================================================
void ApplyOscillLabelColors(void)
{
	lv_obj_set_style_text_color(ui_OscVoltLabel, gPersistData.cvColor, LV_PART_MAIN);
	lv_obj_set_style_text_color(ui_OscAmperLabel, gPersistData.ccColor, LV_PART_MAIN);
}
//===================================================================================================
void ApplyFonts(void)
{
	if (gPersistData.fontIdx < 3) {
		lv_obj_set_style_text_font(ui_uLabel1, fontsArray[gPersistData.fontIdx].big, LV_PART_MAIN);  	
		lv_obj_set_style_text_font(ui_iLabel1, fontsArray[gPersistData.fontIdx].big, LV_PART_MAIN);  	
		lv_obj_set_style_text_font(ui_pLabel1, fontsArray[gPersistData.fontIdx].small, LV_PART_MAIN);  	
		lv_obj_set_style_text_font(ui_uLabel2, fontsArray[gPersistData.fontIdx].small, LV_PART_MAIN);  	
		lv_obj_set_style_text_font(ui_iLabel2, fontsArray[gPersistData.fontIdx].small, LV_PART_MAIN);  	
		lv_obj_set_style_text_font(ui_uLabel3, fontsArray[gPersistData.fontIdx].small, LV_PART_MAIN);  	
		lv_obj_set_style_text_font(ui_iLabel3, fontsArray[gPersistData.fontIdx].small, LV_PART_MAIN);  	
		lv_obj_set_style_text_font(ui_TextAreaUset, fontsArray[gPersistData.fontIdx].small, LV_PART_MAIN);  	
		lv_obj_set_style_text_font(ui_TextAreaIset, fontsArray[gPersistData.fontIdx].small, LV_PART_MAIN);  	
		lv_obj_set_style_text_font(ui_ExampleLabel, fontsArray[gPersistData.fontIdx].small, LV_PART_MAIN);  	
	}
}
//===================================================================================================
void ui_AfterInit(void)
{
  	ApplyBackgroundColors();
	ApplyOscillLabelColors();
	ApplyFonts();

	lv_keyboard_set_map(ui_SetKeyboard, LV_KEYBOARD_MODE_USER_1, kb_map, kb_ctrl);
	lv_label_set_text(ui_WifiSimbolLabel1, LV_SYMBOL_WIFI);
	lv_label_set_text(ui_WifiSimbolLabel2, LV_SYMBOL_WIFI);
 	lv_label_set_text(ui_WifiSimbolLabel3, LV_SYMBOL_WIFI);
 	lv_label_set_text(ui_WifiSimbolLabel4, LV_SYMBOL_WIFI);
 
	lv_obj_set_style_bg_img_src(ui_WifiButton, LV_SYMBOL_SETTINGS, 0);
	lv_obj_set_style_bg_img_src(ui_WifiCloseButton, LV_SYMBOL_CLOSE, 0);
	lv_obj_set_style_bg_img_src(ui_PasswordCloseButton, LV_SYMBOL_CLOSE, 0);
	lv_obj_set_style_bg_img_src(ui_ExteriorMenuButton, LV_SYMBOL_SETTINGS, 0);
	lv_obj_set_style_bg_img_src(ui_ExteriorCloseButton, LV_SYMBOL_CLOSE, 0);

	lv_obj_set_style_bg_img_src(ui_ShiftPlusButton, LV_SYMBOL_PLUS, 0);
	lv_obj_set_style_bg_img_src(ui_ShiftMinusButton, LV_SYMBOL_MINUS, 0);
	lv_obj_set_style_bg_img_src(ui_PrescalerPlusButton, LV_SYMBOL_PLUS, 0);
	lv_obj_set_style_bg_img_src(ui_PrescalerMinusButton, LV_SYMBOL_MINUS, 0);

	ui_WifiList = lv_list_create(ui_WifiScreen);
	lv_obj_set_size(ui_WifiList, 360, 250);
	lv_obj_align_to(ui_WifiList, ui_WifiStatusLabel, LV_ALIGN_TOP_LEFT, 0, 30);
	
	ui_WifiSpinner = lv_spinner_create(ui_WifiScreen, 1000, 60);
    lv_obj_set_size(ui_WifiSpinner, 100, 100);
	lv_obj_align_to(ui_WifiSpinner, ui_WifiScreen, LV_ALIGN_CENTER, -50, 15);

	lv_slider_set_range(ui_BrightnesSlider, 0, 255 / BRIGHTNESS_STEP);
	lv_slider_set_range(ui_ScreensaverSlider, 0, sizeof (gScreensaverArray) - 1);
}
//===============================================================================================
void LoadPreviousScreen(void)
{
	lv_obj_t * scr = lv_scr_act();
	if (scr == ui_SettingsScreen)
		SettingsScreenGestureUpDownEvent_cb(NULL);
	else lv_scr_load_anim(prevScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 1000, 0, false);
}
//===============================================================================================
void DebugScreenUpdateErrors(void)
{
	lv_label_set_text_fmt(ui_InterErrLabel, "Timeouts %d", gInterruptTimeoutErrorCounter);	
	lv_label_set_text_fmt(ui_ValueErrLabel, "Errors %d", gValueErrorCounter);	
}
//===============================================================================================
void uLabelClickEvent_cb(lv_event_t * e)
{
	if (gPersistData.useUART && !gModbusConnected) {
		if (!gData.outputOn || !gPersistData.blockUART) {
			setVoltage = true;
			prevScreen = lv_scr_act();
			char str[8];
			uint16toStr(gVerifiedData.iSet, str, gVerifiedData.iPointPosSet, -1, false);
			lv_obj_remove_event_cb(ui_TextAreaIset, ui_event_TextAreaIset);
			lv_textarea_set_text(ui_TextAreaIset, str);
			lv_obj_set_style_border_color(ui_TextAreaIset, CLR_DARKGRAY, LV_PART_MAIN);
			lv_obj_set_style_shadow_color(ui_TextAreaIset, bgColorsArray[gPersistData.bgColorIdx], LV_PART_MAIN);	

			lv_keyboard_set_textarea(ui_SetKeyboard, ui_TextAreaUset);
			lv_textarea_set_text(ui_TextAreaUset, "");
			lv_obj_set_style_border_color(ui_TextAreaUset, CLR_SHADOW, LV_PART_MAIN);
			lv_obj_set_style_shadow_color(ui_TextAreaUset, CLR_SHADOW, LV_PART_MAIN);
			lv_obj_add_event_cb(ui_TextAreaUset, ui_event_TextAreaUset, LV_EVENT_ALL, NULL);
			lv_obj_add_state(ui_ButtonOk, LV_STATE_DISABLED); 
			lv_scr_load(ui_SetScreen);
			doBeep();
		}
	}
}

void iLabelClickEvent_cb(lv_event_t * e)
{
	if (gPersistData.useUART && !gModbusConnected) {
		if (!gData.outputOn || !gPersistData.blockUART) {
			setVoltage = false;
			prevScreen = lv_scr_act();
			char str[8];
			uint16toStr(gVerifiedData.uSet, str, gVerifiedData.uPointPos, -1, false);
			lv_obj_remove_event_cb(ui_TextAreaUset, ui_event_TextAreaUset);
			lv_textarea_set_text(ui_TextAreaUset, str);
			lv_obj_set_style_border_color(ui_TextAreaUset, CLR_DARKGRAY, LV_PART_MAIN);
			lv_obj_set_style_shadow_color(ui_TextAreaUset, bgColorsArray[gPersistData.bgColorIdx], LV_PART_MAIN);	
			
			lv_keyboard_set_textarea(ui_SetKeyboard, ui_TextAreaIset);
			lv_textarea_set_text(ui_TextAreaIset, "");
			lv_obj_set_style_border_color(ui_TextAreaIset, CLR_SHADOW, LV_PART_MAIN);
			lv_obj_set_style_shadow_color(ui_TextAreaIset, CLR_SHADOW, LV_PART_MAIN);
			lv_obj_add_event_cb(ui_TextAreaIset, ui_event_TextAreaIset, LV_EVENT_ALL, NULL);
			lv_obj_add_state(ui_ButtonOk, LV_STATE_DISABLED); 
			lv_scr_load(ui_SetScreen);		
			doBeep();
		}
	}
}

void wButtonClickEvent_cb(lv_event_t * e)
{
	if (lv_scr_act() == ui_Screen1) {
		showWatt = !showWatt;
		if (showWatt) {
			pLabel = ui_pLabel1;
			rLabel = NULL;
			lv_label_set_text(ui_wLabel1, "W");
			updatePIndicator(true);
		}	
		else {
			pLabel = NULL;
			rLabel = ui_pLabel1;
			lv_label_set_text(ui_wLabel1, "R");
			updateRIndicator(true);
		}
		doBeep();
	}
}

void Screen1LoadStartEvent_cb(lv_event_t * e)
{
	prevScreen = ui_Screen1;
	memcpy(&locPersistData, &gPersistData, sizeof(locPersistData));
	uLabel =ui_uLabel1;
	iLabel = ui_iLabel1;
	ovpLabel = ui_ovpLabel1;
	ocpLabel =ui_ocpLabel1;
	cvLabel = ui_cvLabel1;
	ccLabel = ui_ccLabel1;
	mLabel = ui_mLabel1; 
	outLabel = ui_outLabel1;
	uBar = ui_uBar1;
	iBar = ui_iBar1;
	ahLabel = NULL; 
	whLabel = NULL; 
	tLabel = NULL; 
	wifiLabel = ui_WifiSimbolLabel1; 
	logoLabel = ui_logoLabel1; 

	if (showWatt) {
		pLabel = ui_pLabel1;
		rLabel = NULL;
	}	
	else {
		pLabel = NULL;
		rLabel = ui_pLabel1;
	}
	gFullUpdate = true;
}

void Screen2LoadStartEvent_cb(lv_event_t * e)
{
	prevScreen = ui_Screen2;
	memcpy(&locPersistData, &gPersistData, sizeof(locPersistData));
	uLabel =ui_uLabel2;
	iLabel = ui_iLabel2;
	pLabel = ui_pLabel2;
	rLabel = ui_rLabel2;
	ovpLabel = ui_ovpLabel2;
	ocpLabel =ui_ocpLabel2;
	cvLabel = ui_cvLabel2;
	ccLabel = ui_ccLabel2;
	mLabel = ui_mLabel2; 
	outLabel = ui_outLabel2;
	uBar = NULL;
	iBar = NULL;
	ahLabel = ui_ahLabel2; 
	whLabel = ui_whLabel2; 
	tLabel = ui_tLabel2; 
	wifiLabel = ui_WifiSimbolLabel2; 
	logoLabel = ui_logoLabel2; 
	
	gFullUpdate = true;
	UpdateEnergyLabels();

}

void Screen3LoadStartEvent_cb(lv_event_t * e)
{
	prevScreen = ui_Screen3;
	memcpy(&locPersistData, &gPersistData, sizeof(locPersistData));
	uLabel =ui_uLabel3;
	iLabel = ui_iLabel3;
	pLabel = NULL;
	rLabel = NULL;
	ovpLabel = ui_ovpLabel3;
	ocpLabel =ui_ocpLabel3;
	cvLabel = ui_cvLabel3;
	ccLabel = ui_ccLabel3;
	mLabel = ui_mLabel3; 
	outLabel = ui_outLabel3;
	uBar = NULL;
	iBar = NULL;
	ahLabel = NULL; 
	whLabel = NULL; 
	tLabel = NULL; 
	wifiLabel = ui_WifiSimbolLabel3; 
	logoLabel = ui_logoLabel3; 
	
	gFullUpdate = true;
}

void Screen3LoadedEvent_cb(lv_event_t * e)
{
	gDrawOscill = true;
}

void Screen3UnloadStartEvent(lv_event_t * e)
{
	gDrawOscill = false;
}

void UsetEvent_cb(lv_event_t * e)
{
	const char * text = lv_textarea_get_text(ui_TextAreaUset);
	uint32_t value = strToUint(text, 1);
	if (value > MAX_U) { 
		lv_obj_set_style_text_color(ui_TextAreaUset, lv_palette_main(LV_PALETTE_ORANGE), LV_PART_MAIN);
		lv_obj_add_state(ui_ButtonOk, LV_STATE_DISABLED);       /// States
	}
	else {
		lv_obj_set_style_text_color(ui_TextAreaUset, CLR_WHITE, LV_PART_MAIN);
		lv_obj_clear_state(ui_ButtonOk, LV_STATE_DISABLED);       /// States
		locUset = value;
	}
}

void IsetEvent_cb(lv_event_t * e)
{
	const char * text = lv_textarea_get_text(ui_TextAreaIset);
	uint32_t value = strToUint(text, 0);
	if (value > MAX_I) { 
		lv_obj_set_style_text_color(ui_TextAreaIset, lv_palette_main(LV_PALETTE_ORANGE), LV_PART_MAIN);
		lv_obj_add_state(ui_ButtonOk, LV_STATE_DISABLED);       /// States
	}
	else {
		lv_obj_set_style_text_color(ui_TextAreaIset, CLR_WHITE, LV_PART_MAIN);
		lv_obj_clear_state(ui_ButtonOk, LV_STATE_DISABLED);       /// States
		locIset = value;
	}
}

void OkButtonEvent_cb(lv_event_t * e)
{
	if (!gData.outputOn ||  !gPersistData.blockUART)  // if not block
	{
		if (setVoltage) 
		{
			transmitKoradCommand(locUset, gVerifiedData.iSet, gData.outputOn);
			gVerifiedData.uSet = locUset;
		}
		else 
		{
			transmitKoradCommand(gVerifiedData.uSet, locIset, gData.outputOn);
			gVerifiedData.iSet = locIset;
		}
	}
	lv_scr_load(prevScreen);
	doBeep();
}

void CancelButtonEvent_cb(lv_event_t * e)
{
	lv_scr_load(prevScreen);
	doBeep();
}

void SettingsScreenLoadStartEvent_cb(lv_event_t * e)
{
	gPersistData.wifi ? lv_obj_add_state(ui_WifiMenuSwitch, LV_STATE_CHECKED) : lv_obj_clear_state(ui_WifiMenuSwitch, LV_STATE_CHECKED);
	gPersistData.wifi ?	lv_obj_clear_state(ui_WifiButton, LV_STATE_DISABLED) : lv_obj_add_state(ui_WifiButton, LV_STATE_DISABLED);
	gPersistData.wifi ?	lv_obj_clear_state(ui_WifiIpLabel, LV_STATE_DISABLED) : lv_obj_add_state(ui_WifiIpLabel, LV_STATE_DISABLED);
	gPersistData.useUART ?  lv_obj_add_state(ui_UartSwitch, LV_STATE_CHECKED) : lv_obj_clear_state(ui_UartSwitch, LV_STATE_CHECKED);
	gPersistData.useUART ?  lv_obj_clear_state(ui_BlockUartSwitch, LV_STATE_DISABLED) : lv_obj_add_state(ui_BlockUartSwitch, LV_STATE_DISABLED);
	gPersistData.blockUART ?  lv_obj_add_state(ui_BlockUartSwitch, LV_STATE_CHECKED) : lv_obj_clear_state(ui_BlockUartSwitch, LV_STATE_CHECKED);
	gPersistData.autoReset ? lv_obj_add_state(ui_AutoResetSwitch, LV_STATE_CHECKED) : lv_obj_clear_state(ui_AutoResetSwitch, LV_STATE_CHECKED);

	lv_slider_set_value(ui_ScreensaverSlider, gPersistData.ScreensaverIdx, LV_ANIM_OFF);
	ScreensaverSliderEvent_cb(NULL);
	lv_slider_set_value(ui_BeeperSlider, gPersistData.beeperVolume, LV_ANIM_OFF);
	BeeperSliderEvent_cb(NULL);

	if (gNetworkStatus == NETWORK_CONNECTED) {
		uint8_t * ip;
		ip = (uint8_t *) &locIPaddress;
		lv_label_set_text_fmt(ui_WifiIpLabel, "IP %3d.%3d.%3d.%3d", ip[0], ip[1], ip[2], ip[3]);
	} 
	else {
		lv_label_set_text(ui_WifiIpLabel, "Not connected");
	}
}

void ScreensaverSliderEvent_cb(lv_event_t * e)
{
	uint8_t idx = lv_slider_get_value(ui_ScreensaverSlider);
	if (idx == 0) lv_label_set_text(ui_ScreensaverLabel, "Off");
	else lv_label_set_text_fmt(ui_ScreensaverLabel, "%d min.", gScreensaverArray[idx]);
	if (e != NULL) {
		doBeep();
		gPersistData.ScreensaverIdx = idx;
	}
}

void BeeperSliderEvent_cb(lv_event_t * e)
{
	uint8_t idx = lv_slider_get_value(ui_BeeperSlider);
	if (idx == 0) lv_label_set_text(ui_BeeperLabel, "Off");
	else lv_label_set_text_fmt(ui_BeeperLabel, "%d %%", idx * 20);
	if (e != NULL) {
		doBeep();
		gPersistData.beeperVolume = idx;
	}
}

void UartSwitchClicedEvent_cb(lv_event_t * e)
{
	lv_obj_has_state(ui_UartSwitch, LV_STATE_CHECKED) ?  lv_obj_clear_state(ui_BlockUartSwitch, LV_STATE_DISABLED) : lv_obj_add_state(ui_BlockUartSwitch, LV_STATE_DISABLED);
	doBeep();
}

void SettingsScreenGestureUpDownEvent_cb(lv_event_t * e)
{
	bool state = lv_obj_has_state(ui_UartSwitch, LV_STATE_CHECKED);
	bool res = state != gPersistData.useUART;
	if (res) uartBeginEnd(state);
	gPersistData.useUART = state;

	state = lv_obj_has_state(ui_BlockUartSwitch, LV_STATE_CHECKED);
	res |= state != gPersistData.blockUART;
	gPersistData.blockUART = state;

	state = lv_obj_has_state(ui_AutoResetSwitch, LV_STATE_CHECKED);
	res |= state != gPersistData.autoReset;
	gPersistData.autoReset = state;

	res |= locPersistData.wifi != gPersistData.wifi;
	res |= locPersistData.reconnect != gPersistData.reconnect;
	res |= locPersistData.fontIdx != gPersistData.fontIdx;
	res |= locPersistData.bgColorIdx != gPersistData.bgColorIdx;
	res |= locPersistData.brightness != gPersistData.brightness;
	res |= locPersistData.ScreensaverIdx != gPersistData.ScreensaverIdx;
	res |= locPersistData.beeperVolume != gPersistData.beeperVolume;
	res |= locPersistData.ccColor.full != gPersistData.ccColor.full;
	res |= locPersistData.cvColor.full != gPersistData.cvColor.full;
	res |= locPersistData.offColor.full != gPersistData.offColor.full;
	res |= locPersistData.pwrColor.full != gPersistData.pwrColor.full;
	res |= locPersistData.resColor.full != gPersistData.resColor.full;
	
	if (res) SavePersistentData(); 
	lv_obj_clean(ui_WifiList); 
	if (e == NULL) 	lv_scr_load_anim(prevScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 1000, 0, false);
	else lv_scr_load(prevScreen);
}

void DebugScreenLoadStartEvent_cb(lv_event_t * e)
{
	uLabel =ui_uLabel4;
	iLabel = ui_iLabel4;
	pLabel = NULL;
	rLabel = NULL;
	ovpLabel = ui_ovpLabel4;
	ocpLabel =ui_ocpLabel4;
	cvLabel = ui_cvLabel4;
	ccLabel = ui_ccLabel4;
	mLabel = ui_mLabel4; 
	outLabel = ui_outLabel4;
	uBar = NULL;
	iBar = NULL;
	ahLabel = NULL; 
	whLabel = NULL; 
	tLabel = NULL; 
	wifiLabel = ui_WifiSimbolLabel4; 
	logoLabel = NULL; 
	
	gFullUpdate = true;
	gBeeperEnable = false;
	lv_spinbox_set_value(ui_PrescalerSpinbox, gPersistData.prescaler);
	lv_spinbox_set_value(ui_ShiftSpinbox, gPersistData.shiftData);
	gPersistData.reversData ?  lv_obj_add_state(ui_ReversCheckbox, LV_STATE_CHECKED) : lv_obj_clear_state(ui_ReversCheckbox, LV_STATE_CHECKED);
	gPersistData.beforeEdge ? lv_dropdown_set_selected(ui_EdgeDropdown, 0) : lv_dropdown_set_selected(ui_EdgeDropdown, 1);
	gValueErrorCounter = 0;
	gInterruptTimeoutErrorCounter = 0;
	gBeeperEnable = true;
}

void DebugScreenGesureUpDownEvent_cb(lv_event_t * e)
{
	gPersistData.prescaler = locPersistData.prescaler;         
	gPersistData.shiftData = locPersistData.shiftData;
	gPersistData.beforeEdge = locPersistData.beforeEdge;
	lv_scr_load(prevScreen);
}

void ShiftSpinboxEvent_cb(lv_event_t * e)
{
	gPersistData.shiftData = lv_spinbox_get_value(ui_ShiftSpinbox);
	doBeep();
}

void ReversCheckboxEvent_cb(lv_event_t * e)
{
	gPersistData.reversData = lv_obj_has_state(ui_ReversCheckbox, LV_STATE_CHECKED);
	doBeep();
}

void EdgeDropdownEvent_cb(lv_event_t * e)
{
	gPersistData.beforeEdge = lv_dropdown_get_selected(ui_EdgeDropdown) == 0;
	doBeep();
}

void PrescalerSpinboxValueChangedEvent_cb(lv_event_t * e)
{
	gPersistData.prescaler = lv_spinbox_get_value(ui_PrescalerSpinbox);
	doBeep();
}

void SaveButtonClickEvent_cb(lv_event_t * e)
{
	SavePersistentData();
	lv_scr_load(prevScreen);
	doBeep();
}

void onWifiTimer(lv_timer_t *timer) 
{
  	LV_UNUSED(timer);
	uint8_t  * ip;
	updateWifiList();
  	switch (gNetworkStatus) {
		case NETWORK_DISCONNECTED:
			lv_label_set_text(ui_WifiStatusLabel, "Select network");
			lv_label_set_text(ui_WifiSsidNameLabel, "");
			break;

		case NETWORK_CONNECTING:
			lv_label_set_text(ui_WifiStatusLabel, "Try connect to");
			lv_label_set_text(ui_WifiSsidNameLabel, "previous network");
			lv_label_set_text(ui_PasswordLabel, "Connecting ...");
			break;

		case NETWORK_WAIT_IP:
			lv_label_set_text(ui_WifiStatusLabel, "Waiting for IP");
			lv_label_set_text(ui_WifiSsidNameLabel, "");
			lv_label_set_text(ui_PasswordLabel, "Waiting for IP");
			break;

		case NETWORK_CONNECTED:
			lv_label_set_text(ui_WifiStatusLabel, "Connected to");
			lv_label_set_text(ui_WifiSsidNameLabel, locSsidName);

			char str[64] = "Connected to ";
			strcat(str, locSsidName);
			lv_label_set_text_fmt(ui_PasswordLabel, str);
			lv_obj_clear_state(ui_PasswordCloseButton, LV_STATE_DISABLED);
			gPersistData.reconnect = true;
			break;

		case NETWORK_CONNECT_FAILED:
			lv_label_set_text(ui_WifiStatusLabel, "Select network");
			lv_label_set_text(ui_WifiSsidNameLabel, "");
			lv_label_set_text(ui_PasswordLabel, "Oops!  Please check your wifi password and try again.");
			lv_obj_clear_state(ui_PasswordCloseButton, LV_STATE_DISABLED);
			lv_obj_clear_state(ui_PasswordTextArea, LV_STATE_DISABLED);
			lv_obj_clear_state(ui_PasswordConnectButton, LV_STATE_DISABLED);
			gPersistData.reconnect = false;
			break;

		default:
			break;
  }
}

void WifiButtonClickEvent_cb(lv_event_t * e)
{
	lv_scr_load(ui_WifiScreen);
	wifiTimer = lv_timer_create(onWifiTimer, 1000, NULL);
	if (lv_obj_get_child_cnt(ui_WifiList) == 0) {
		lv_list_add_text(ui_WifiList, "Searching . . .");
		lv_obj_clear_flag(ui_WifiSpinner, LV_OBJ_FLAG_HIDDEN);
	}
	changeNetworkTask(NETWORK_TASK_SCAN);
	doBeep();
}

void WifiMenuSwitchEvent_cb(lv_event_t * e)
{
	gPersistData.wifi = lv_obj_has_state(ui_WifiMenuSwitch, LV_STATE_CHECKED);
	if (gPersistData.wifi) {
		lv_obj_clear_state(ui_WifiButton, LV_STATE_DISABLED);
		lv_obj_clear_state(ui_WifiIpLabel, LV_STATE_DISABLED);
		if (gPersistData.reconnect) 
			changeNetworkTask(NETWORK_TASK_MAIN);
		else WifiButtonClickEvent_cb(e);
	}
	else {
		lv_obj_add_state(ui_WifiButton, LV_STATE_DISABLED);
		lv_obj_add_state(ui_WifiIpLabel, LV_STATE_DISABLED);
		changeNetworkTask(NETWORK_TASK_STOP);	
	}
	doBeep();
}

void WifiScreenLoadStartEvent_cb(lv_event_t * e)
{
	if (gNetworkStatus == NETWORK_CONNECTED) {
		lv_label_set_text(ui_WifiStatusLabel, "Connected to");
		lv_label_set_text(ui_WifiSsidNameLabel, locSsidName);
	}
	else {
		lv_label_set_text(ui_WifiStatusLabel, "Not Connected");
		lv_label_set_text(ui_WifiSsidNameLabel, "");
	}

}

void WifiCloseButton_cb(lv_event_t * e)
{
    gPersistData.wifi = gNetworkStatus == NETWORK_CONNECTED;
	if (gPersistData.wifi) changeNetworkTask(NETWORK_TASK_MAIN);
	else changeNetworkTask(NETWORK_TASK_STOP);
	lv_timer_del(wifiTimer);
	lv_scr_load(ui_SettingsScreen);
	doBeep();
}

void PasswordTextAreaFocusedEvent_cb(lv_event_t * e)
{
    lv_obj_move_foreground(ui_PasswordKeyboard);
    lv_keyboard_set_textarea(ui_PasswordKeyboard, ui_PasswordTextArea);
    lv_obj_clear_flag(ui_PasswordKeyboard, LV_OBJ_FLAG_HIDDEN);
}

void PasswordKeyboardReadyEvent_cb(lv_event_t * e)
{
    lv_keyboard_set_textarea(ui_PasswordKeyboard, NULL);
    lv_obj_add_flag(ui_PasswordKeyboard, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_state(ui_PasswordConnectButton, LV_STATE_DISABLED);
}

void PasswordCloseButton_cb(lv_event_t * e)
{
	lv_timer_resume(wifiTimer);
	if (gNetworkStatus == NETWORK_CONNECTED)  {
		WifiCloseButton_cb(e);
	}
	else {
		changeNetworkTask(NETWORK_TASK_SCAN);
		lv_scr_load(ui_WifiScreen);
		doBeep();
	}
}

void PasswordConnectButton_cb(lv_event_t * e)
{
	memset(tmpSsidPassword, 0, sizeof(tmpSsidPassword)); 
	const char * str = lv_textarea_get_text(ui_PasswordTextArea);
	strncpy(tmpSsidPassword, str, strlen(str)); 
	changeNetworkTask(NETWORK_TASK_CONNECT);	// new connection	
	lv_label_set_text(ui_PasswordLabel, "Connecting...");
	lv_obj_add_state(ui_PasswordCloseButton, LV_STATE_DISABLED);
	lv_obj_add_state(ui_PasswordTextArea, LV_STATE_DISABLED);
	lv_obj_add_state(ui_PasswordConnectButton, LV_STATE_DISABLED);
	lv_timer_resume(wifiTimer);
}

void ExteriorMenuButtonClickEvent_cb(lv_event_t * e)
{
	lv_scr_load(ui_ExteriorScreen);
	ColorDropdownEvent_cb(e);
	lv_slider_set_value(ui_BrightnesSlider, gPersistData.brightness / BRIGHTNESS_STEP, 0);
	lv_slider_set_value(ui_BackgroundSlider, gPersistData.bgColorIdx, 0);
	lv_dropdown_set_selected(ui_FontDropdown, gPersistData.fontIdx);
	doBeep();
}


void ColorwheelEvent_cb(lv_event_t * e)
{
	lv_color_t color = lv_colorwheel_get_rgb(ui_Colorwheel);
	lv_obj_set_style_text_color(ui_ExampleLabel, color, LV_PART_MAIN);
	int16_t idx = lv_dropdown_get_selected(ui_ColorDropdown);
	switch (idx) {
		case 0: // CV
			gPersistData.cvColor = color; 
			break;
		case 1: // CC
			gPersistData.ccColor = color; 
			break;
		case 2: // OFF
			gPersistData.offColor = color; 
			break;
		case 3: // RES
			gPersistData.resColor = color; 
			break;
		case 4: // PWR
			gPersistData.pwrColor = color; 
			break;
	}

	doBeep();
}

void ColorDropdownEvent_cb(lv_event_t * e)
{
	lv_color_t color;	
	int16_t idx = lv_dropdown_get_selected(ui_ColorDropdown);
	lv_colorwheel_set_mode(ui_Colorwheel, LV_COLORWHEEL_MODE_HUE);
	switch (idx) {
		case 0: // CV
			color = gPersistData.cvColor; 
			lv_obj_set_style_text_color(ui_ExampleLabel, color, LV_PART_MAIN);
			lv_colorwheel_set_rgb(ui_Colorwheel, color);
			break;
		case 1: // CC
			color = gPersistData.ccColor; 
			lv_obj_set_style_text_color(ui_ExampleLabel, color, LV_PART_MAIN);
			lv_colorwheel_set_rgb(ui_Colorwheel, color);
			break;
		case 2: // OFF
			color = gPersistData.offColor; 
			lv_obj_set_style_text_color(ui_ExampleLabel, color, LV_PART_MAIN);
			lv_colorwheel_set_rgb(ui_Colorwheel, color);
			break;
		case 3: // RES
			color = gPersistData.resColor; 
			lv_obj_set_style_text_color(ui_ExampleLabel, color, LV_PART_MAIN);
			lv_colorwheel_set_rgb(ui_Colorwheel, color);
			break;
		case 4: // PWR
			color = gPersistData.pwrColor; 
			lv_obj_set_style_text_color(ui_ExampleLabel, color, LV_PART_MAIN);
			lv_colorwheel_set_rgb(ui_Colorwheel, color);
			break;
	}
	doBeep();
}

void BackgroundSliderEvent_cb(lv_event_t * e)
{
	gPersistData.bgColorIdx = (uint8_t)lv_slider_get_value(ui_BackgroundSlider);
	ApplyBackgroundColors();
	doBeep();
}

void BrightnesSliderEvent_cb(lv_event_t * e)
{
  	uint8_t steps = (uint8_t)lv_slider_get_value(ui_BrightnesSlider);
	gPersistData.brightness = steps * BRIGHTNESS_STEP;
  	setBrightness(gPersistData.brightness);
	doBeep();
}

void ExteriorCloseButton_cb(lv_event_t * e)
{
	ApplyOscillLabelColors();
	oscInitColors();
	doBeep();
	SettingsScreenGestureUpDownEvent_cb(e);
}

void FontDropdownEvent_cb(lv_event_t * e)
{
	gPersistData.fontIdx = lv_dropdown_get_selected(ui_FontDropdown); 
	ApplyFonts();
	doBeep();
}


void DefaultButtonClickEvent_cb(lv_event_t * e)
{
	initCommonData();
	ColorDropdownEvent_cb(e);
	lv_slider_set_value(ui_BackgroundSlider, 3, 0);
	doBeep();
}

void OscillPanelClickEvent_cb(lv_event_t * e)
{
	uint16_t xposV, xposA;
	if (gOscMode == 3) gOscMode = 7;
	else if (gOscMode == 7) gOscMode = 1;
	else gOscMode++;
	if ((gOscMode & 4) == 0) { xposV = 40; xposA = 300;}
	else { xposV = 300; xposA = 40;}
	lv_obj_set_pos(ui_OscVoltLabel, xposV, 224);
	lv_obj_set_pos(ui_OscAmperLabel, xposA, 224);
	if (gOscMode & 1) lv_obj_clear_flag(ui_OscVoltLabel, LV_OBJ_FLAG_HIDDEN);
	else lv_obj_add_flag(ui_OscVoltLabel, LV_OBJ_FLAG_HIDDEN);
	if (gOscMode & 2) lv_obj_clear_flag(ui_OscAmperLabel, LV_OBJ_FLAG_HIDDEN);
	else lv_obj_add_flag(ui_OscAmperLabel, LV_OBJ_FLAG_HIDDEN);
	doBeep();
}

void JustDoBeepEvent_cb(lv_event_t * e)
{
	doBeep();
}
