// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: KORAD_Project

#include "ui.h"

void ui_ExteriorScreen_screen_init(void)
{
    ui_ExteriorScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ExteriorScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ExamplePanel = lv_obj_create(ui_ExteriorScreen);
    lv_obj_set_width(ui_ExamplePanel, 242);
    lv_obj_set_height(ui_ExamplePanel, 302);
    lv_obj_set_x(ui_ExamplePanel, 7);
    lv_obj_set_y(ui_ExamplePanel, 0);
    lv_obj_set_align(ui_ExamplePanel, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ExamplePanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Colorwheel = lv_colorwheel_create(ui_ExamplePanel, true);
    lv_obj_set_width(ui_Colorwheel, 186);
    lv_obj_set_height(ui_Colorwheel, 186);
    lv_obj_set_x(ui_Colorwheel, 0);
    lv_obj_set_y(ui_Colorwheel, 28);
    lv_obj_set_align(ui_Colorwheel, LV_ALIGN_CENTER);

    lv_obj_set_style_border_color(ui_Colorwheel, lv_color_hex(0x28DCFD), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Colorwheel, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Colorwheel, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ColorDropdown = lv_dropdown_create(ui_ExamplePanel);
    lv_dropdown_set_options(ui_ColorDropdown, "CV  color\nCC  color\nOFF color\nRES color\nPWR color");
    lv_obj_set_width(ui_ColorDropdown, 150);
    lv_obj_set_height(ui_ColorDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ColorDropdown, 24);
    lv_obj_set_y(ui_ColorDropdown, 0);
    lv_obj_set_align(ui_ColorDropdown, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ColorDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_ExampleLabel = lv_label_create(ui_ExamplePanel);
    lv_obj_set_width(ui_ExampleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ExampleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ExampleLabel, -3);
    lv_obj_set_y(ui_ExampleLabel, 2);
    lv_label_set_text(ui_ExampleLabel, "5");
    lv_obj_set_style_text_font(ui_ExampleLabel, &ui_font_Segment38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ExteriorCloseButton = lv_btn_create(ui_ExteriorScreen);
    lv_obj_set_width(ui_ExteriorCloseButton, 58);
    lv_obj_set_height(ui_ExteriorCloseButton, 50);
    lv_obj_set_x(ui_ExteriorCloseButton, -8);
    lv_obj_set_y(ui_ExteriorCloseButton, 20);
    lv_obj_set_align(ui_ExteriorCloseButton, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ExteriorCloseButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ExteriorCloseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ExteriorCloseButton, lv_color_hex(0x7689AC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ExteriorCloseButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ExteriorCloseButton, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ExteriorCloseButton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ExteriorCloseButton, lv_color_hex(0x28DCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ExteriorCloseButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ExteriorCloseButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ExteriorCloseButton, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DefaultButton = lv_btn_create(ui_ExteriorScreen);
    lv_obj_set_width(ui_DefaultButton, 100);
    lv_obj_set_height(ui_DefaultButton, 50);
    lv_obj_set_x(ui_DefaultButton, 155);
    lv_obj_set_y(ui_DefaultButton, 111);
    lv_obj_set_align(ui_DefaultButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DefaultButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DefaultButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DefaultButton, lv_color_hex(0x7689AC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DefaultButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_DefaultButton, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_DefaultButton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DefaultButton, lv_color_hex(0x28DCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DefaultButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DefaultButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_DefaultButton);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Default");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FontDropdown = lv_dropdown_create(ui_ExteriorScreen);
    lv_dropdown_set_options(ui_FontDropdown, "Segment\nElectro\nRoboto");
    lv_obj_set_width(ui_FontDropdown, 133);
    lv_obj_set_height(ui_FontDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FontDropdown, 88);
    lv_obj_set_y(ui_FontDropdown, -116);
    lv_obj_set_align(ui_FontDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FontDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_BackgroundSlider = lv_slider_create(ui_ExteriorScreen);
    lv_slider_set_range(ui_BackgroundSlider, 0, 4);
    lv_obj_set_width(ui_BackgroundSlider, 162);
    lv_obj_set_height(ui_BackgroundSlider, 10);
    lv_obj_set_x(ui_BackgroundSlider, -30);
    lv_obj_set_y(ui_BackgroundSlider, -37);
    lv_obj_set_align(ui_BackgroundSlider, LV_ALIGN_RIGHT_MID);

    lv_obj_set_style_bg_color(ui_BackgroundSlider, lv_color_hex(0x222222), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackgroundSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BackgroundSlider, lv_color_hex(0x1DE8FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BackgroundSlider, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BackgroundSlider, lv_color_hex(0x7689AC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackgroundSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BackgroundSlider, lv_color_hex(0x222222), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BackgroundSlider, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackgroundSlider, lv_color_hex(0x28DCFD), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackgroundSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackgroundSlider, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BrightnesSlider = lv_slider_create(ui_ExteriorScreen);
    lv_slider_set_range(ui_BrightnesSlider, 20, 255);
    lv_obj_set_width(ui_BrightnesSlider, 162);
    lv_obj_set_height(ui_BrightnesSlider, 10);
    lv_obj_set_x(ui_BrightnesSlider, -30);
    lv_obj_set_y(ui_BrightnesSlider, 32);
    lv_obj_set_align(ui_BrightnesSlider, LV_ALIGN_RIGHT_MID);

    lv_obj_set_style_bg_color(ui_BrightnesSlider, lv_color_hex(0x222222), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnesSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BrightnesSlider, lv_color_hex(0x11DDEE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BrightnesSlider, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BrightnesSlider, lv_color_hex(0x776688), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnesSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BrightnesSlider, lv_color_hex(0x222222), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BrightnesSlider, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BrightnesSlider, lv_color_hex(0x28DCFD), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BrightnesSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BrightnesSlider, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_ExteriorScreen);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 121);
    lv_obj_set_y(ui_Label16, -64);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Background");

    ui_Label18 = lv_label_create(ui_ExteriorScreen);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 121);
    lv_obj_set_y(ui_Label18, 5);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Backlight");

    lv_obj_add_event_cb(ui_Colorwheel, ui_event_Colorwheel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ColorDropdown, ui_event_ColorDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ExteriorCloseButton, ui_event_ExteriorCloseButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DefaultButton, ui_event_DefaultButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FontDropdown, ui_event_FontDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackgroundSlider, ui_event_BackgroundSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrightnesSlider, ui_event_BrightnesSlider, LV_EVENT_ALL, NULL);

}
