// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: KORAD_Project

#include "ui.h"

void ui_PasswordScreen_screen_init(void)
{
    ui_PasswordScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PasswordScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PasswordConnectButton = lv_btn_create(ui_PasswordScreen);
    lv_obj_set_width(ui_PasswordConnectButton, 131);
    lv_obj_set_height(ui_PasswordConnectButton, 43);
    lv_obj_set_x(ui_PasswordConnectButton, 11);
    lv_obj_set_y(ui_PasswordConnectButton, 30);
    lv_obj_set_align(ui_PasswordConnectButton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PasswordConnectButton, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_PasswordConnectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PasswordConnectButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PasswordConnectButton, lv_color_hex(0x7689AC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PasswordConnectButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PasswordConnectButton, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PasswordConnectButton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PasswordConnectButton, lv_color_hex(0x28DCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PasswordConnectButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PasswordConnectButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_PasswordConnectButton);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Connect");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PasswordLabel = lv_label_create(ui_PasswordScreen);
    lv_obj_set_width(ui_PasswordLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PasswordLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PasswordLabel, 25);
    lv_obj_set_y(ui_PasswordLabel, 104);

    ui_PasswordTextArea = lv_textarea_create(ui_PasswordScreen);
    lv_obj_set_width(ui_PasswordTextArea, 371);
    lv_obj_set_height(ui_PasswordTextArea, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_PasswordTextArea, 16);
    lv_obj_set_y(ui_PasswordTextArea, 20);
    lv_textarea_set_max_length(ui_PasswordTextArea, 30);
    lv_textarea_set_placeholder_text(ui_PasswordTextArea, "Password");
    lv_textarea_set_one_line(ui_PasswordTextArea, true);
    lv_obj_set_style_text_font(ui_PasswordTextArea, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_PasswordCloseButton = lv_btn_create(ui_PasswordScreen);
    lv_obj_set_width(ui_PasswordCloseButton, 58);
    lv_obj_set_height(ui_PasswordCloseButton, 50);
    lv_obj_set_x(ui_PasswordCloseButton, -8);
    lv_obj_set_y(ui_PasswordCloseButton, 20);
    lv_obj_set_align(ui_PasswordCloseButton, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_PasswordCloseButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PasswordCloseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PasswordCloseButton, lv_color_hex(0x7689AC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PasswordCloseButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PasswordCloseButton, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PasswordCloseButton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PasswordCloseButton, lv_color_hex(0x28DCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PasswordCloseButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PasswordCloseButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PasswordCloseButton, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PasswordKeyboard = lv_keyboard_create(ui_PasswordScreen);
    lv_keyboard_set_mode(ui_PasswordKeyboard, LV_KEYBOARD_MODE_TEXT_UPPER);
    lv_obj_set_width(ui_PasswordKeyboard, 473);
    lv_obj_set_height(ui_PasswordKeyboard, 226);
    lv_obj_set_align(ui_PasswordKeyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_PasswordKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_PasswordConnectButton, ui_event_PasswordConnectButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PasswordTextArea, ui_event_PasswordTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PasswordCloseButton, ui_event_PasswordCloseButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PasswordKeyboard, ui_event_PasswordKeyboard, LV_EVENT_ALL, NULL);

}
