// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: KORAD_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiSimbolLabel3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_WifiSimbolLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiSimbolLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiSimbolLabel3, 4);
    lv_obj_set_y(ui_WifiSimbolLabel3, 2);
    lv_label_set_text(ui_WifiSimbolLabel3, "W");
    lv_obj_set_style_text_color(ui_WifiSimbolLabel3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiSimbolLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logoLabel3 = lv_label_create(ui_Screen3);
    lv_obj_set_height(ui_logoLabel3, 15);
    lv_obj_set_width(ui_logoLabel3, lv_pct(93));
    lv_obj_set_x(ui_logoLabel3, 12);
    lv_obj_set_y(ui_logoLabel3, 2);
    lv_obj_set_align(ui_logoLabel3, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_logoLabel3, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_logoLabel3, "KORAD");
    lv_obj_clear_flag(ui_logoLabel3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_logoLabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_logoLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_logoLabel3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bodyPanel3 = lv_obj_create(ui_Screen3);
    lv_obj_set_height(ui_bodyPanel3, 300);
    lv_obj_set_width(ui_bodyPanel3, lv_pct(100));
    lv_obj_set_x(ui_bodyPanel3, 0);
    lv_obj_set_y(ui_bodyPanel3, 10);
    lv_obj_set_align(ui_bodyPanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_bodyPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bodyPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_bodyPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_bodyPanel3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_bodyPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_bodyPanel3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_bodyPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uLabel3 = lv_label_create(ui_bodyPanel3);
    lv_obj_set_width(ui_uLabel3, 154);
    lv_obj_set_height(ui_uLabel3, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_uLabel3, 7);
    lv_obj_set_y(ui_uLabel3, 232);
    lv_label_set_text(ui_uLabel3, "88.88");
    lv_obj_add_flag(ui_uLabel3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_letter_space(ui_uLabel3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_uLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_uLabel3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uLabel3, &ui_font_Segment38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iLabel3 = lv_label_create(ui_bodyPanel3);
    lv_obj_set_width(ui_iLabel3, 154);
    lv_obj_set_height(ui_iLabel3, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_iLabel3, 297);
    lv_obj_set_y(ui_iLabel3, 232);
    lv_label_set_text(ui_iLabel3, "88.88");
    lv_obj_add_flag(ui_iLabel3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_letter_space(ui_iLabel3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_iLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_iLabel3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iLabel3, &ui_font_Segment38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ovpLabel3 = lv_label_create(ui_bodyPanel3);
    lv_obj_set_width(ui_ovpLabel3, 60);
    lv_obj_set_height(ui_ovpLabel3, 28);
    lv_obj_set_x(ui_ovpLabel3, 390);
    lv_obj_set_y(ui_ovpLabel3, 10);
    lv_label_set_text(ui_ovpLabel3, "OVP");
    lv_obj_set_style_text_color(ui_ovpLabel3, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ovpLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ovpLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ovpLabel3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ovpLabel3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ovpLabel3, lv_color_hex(0x7C7C7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ovpLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ovpLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ovpLabel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ovpLabel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ovpLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cvLabel3 = lv_label_create(ui_bodyPanel3);
    lv_obj_set_width(ui_cvLabel3, 60);
    lv_obj_set_height(ui_cvLabel3, 28);
    lv_obj_set_x(ui_cvLabel3, 390);
    lv_obj_set_y(ui_cvLabel3, 50);
    lv_label_set_text(ui_cvLabel3, "CV");
    lv_obj_set_style_text_color(ui_cvLabel3, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cvLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cvLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cvLabel3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cvLabel3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cvLabel3, lv_color_hex(0x7C7C7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cvLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cvLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cvLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cvLabel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cvLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ocpLabel3 = lv_label_create(ui_bodyPanel3);
    lv_obj_set_width(ui_ocpLabel3, 60);
    lv_obj_set_height(ui_ocpLabel3, 28);
    lv_obj_set_x(ui_ocpLabel3, 390);
    lv_obj_set_y(ui_ocpLabel3, 130);
    lv_label_set_text(ui_ocpLabel3, "OCP");
    lv_obj_set_style_text_color(ui_ocpLabel3, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ocpLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ocpLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ocpLabel3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ocpLabel3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ocpLabel3, lv_color_hex(0x7C7C7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ocpLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ocpLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ocpLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ocpLabel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ocpLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ccLabel3 = lv_label_create(ui_bodyPanel3);
    lv_obj_set_width(ui_ccLabel3, 60);
    lv_obj_set_height(ui_ccLabel3, 28);
    lv_obj_set_x(ui_ccLabel3, 390);
    lv_obj_set_y(ui_ccLabel3, 170);
    lv_label_set_text(ui_ccLabel3, "CC");
    lv_obj_set_style_text_color(ui_ccLabel3, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ccLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ccLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ccLabel3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ccLabel3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ccLabel3, lv_color_hex(0x7C7C7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ccLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ccLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ccLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ccLabel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ccLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outLabel3 = lv_label_create(ui_bodyPanel3);
    lv_obj_set_width(ui_outLabel3, 92);
    lv_obj_set_height(ui_outLabel3, 44);
    lv_obj_set_x(ui_outLabel3, 183);
    lv_obj_set_y(ui_outLabel3, 230);
    lv_label_set_text(ui_outLabel3, "OFF");
    lv_obj_set_style_text_align(ui_outLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_outLabel3, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_outLabel3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_outLabel3, lv_color_hex(0x39CB12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_outLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_outLabel3, lv_color_hex(0x929191), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_outLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_outLabel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_outLabel3, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_outLabel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mLabel3 = lv_label_create(ui_bodyPanel3);
    lv_obj_set_width(ui_mLabel3, 60);
    lv_obj_set_height(ui_mLabel3, 28);
    lv_obj_set_x(ui_mLabel3, 390);
    lv_obj_set_y(ui_mLabel3, 90);
    lv_label_set_text(ui_mLabel3, "MO");
    lv_obj_set_style_text_color(ui_mLabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_mLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mLabel3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_mLabel3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mLabel3, lv_color_hex(0x4411A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_mLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_mLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_mLabel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_mLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OscVoltLabel = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_OscVoltLabel, 60);
    lv_obj_set_height(ui_OscVoltLabel, 14);
    lv_obj_set_x(ui_OscVoltLabel, 40);
    lv_obj_set_y(ui_OscVoltLabel, 224);
    lv_label_set_long_mode(ui_OscVoltLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_OscVoltLabel, "5.00 V/d");
    lv_obj_set_style_text_align(ui_OscVoltLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OscAmperLabel = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_OscAmperLabel, 60);
    lv_obj_set_height(ui_OscAmperLabel, 14);
    lv_obj_set_x(ui_OscAmperLabel, 300);
    lv_obj_set_y(ui_OscAmperLabel, 224);
    lv_label_set_long_mode(ui_OscAmperLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_OscAmperLabel, "1.00 A/d");
    lv_obj_set_style_text_align(ui_OscAmperLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_uLabel3, ui_event_uLabel3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_iLabel3, ui_event_iLabel3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bodyPanel3, ui_event_bodyPanel3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}
