// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: KORAD_Project

#include "ui.h"

void ui_SetScreen_screen_init(void)
{
    ui_SetScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SetScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextAreaUset = lv_textarea_create(ui_SetScreen);
    lv_obj_set_width(ui_TextAreaUset, 182);
    lv_obj_set_height(ui_TextAreaUset, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_TextAreaUset, -133);
    lv_obj_set_y(ui_TextAreaUset, -117);
    lv_obj_set_align(ui_TextAreaUset, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaUset, 5);
    lv_textarea_set_placeholder_text(ui_TextAreaUset, "0");
    lv_textarea_set_one_line(ui_TextAreaUset, true);
    lv_obj_set_style_text_letter_space(ui_TextAreaUset, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TextAreaUset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaUset, &ui_font_Segment38, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TextAreaUset, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TextAreaUset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TextAreaUset, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TextAreaUset, 2, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TextAreaIset = lv_textarea_create(ui_SetScreen);
    lv_obj_set_width(ui_TextAreaIset, 182);
    lv_obj_set_height(ui_TextAreaIset, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_TextAreaIset, 99);
    lv_obj_set_y(ui_TextAreaIset, -118);
    lv_obj_set_align(ui_TextAreaIset, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaIset, 5);
    lv_textarea_set_placeholder_text(ui_TextAreaIset, "0");
    lv_textarea_set_one_line(ui_TextAreaIset, true);
    lv_obj_set_style_text_letter_space(ui_TextAreaIset, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TextAreaIset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaIset, &ui_font_Segment38, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TextAreaIset, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TextAreaIset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TextAreaIset, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TextAreaIset, 2, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_SetKeyboard = lv_keyboard_create(ui_SetScreen);
    lv_keyboard_set_mode(ui_SetKeyboard, LV_KEYBOARD_MODE_USER_1);
    lv_obj_set_height(ui_SetKeyboard, 233);
    lv_obj_set_width(ui_SetKeyboard, lv_pct(70));
    lv_obj_set_x(ui_SetKeyboard, -65);
    lv_obj_set_y(ui_SetKeyboard, -5);

    lv_obj_set_style_text_font(ui_SetKeyboard, &lv_font_montserrat_22, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_ButtonOk = lv_btn_create(ui_SetScreen);
    lv_obj_set_width(ui_ButtonOk, 100);
    lv_obj_set_height(ui_ButtonOk, 50);
    lv_obj_set_x(ui_ButtonOk, 359);
    lv_obj_set_y(ui_ButtonOk, 88);
    lv_obj_add_state(ui_ButtonOk, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_ButtonOk, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonOk, lv_color_hex(0x7689AC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonOk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonOk, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ButtonOk, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonOk, lv_color_hex(0x28DCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonOk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonOk, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_ButtonOk);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "OK");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonCancel = lv_btn_create(ui_SetScreen);
    lv_obj_set_width(ui_ButtonCancel, 100);
    lv_obj_set_height(ui_ButtonCancel, 50);
    lv_obj_set_x(ui_ButtonCancel, 358);
    lv_obj_set_y(ui_ButtonCancel, 198);
    lv_obj_add_flag(ui_ButtonCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonCancel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonCancel, lv_color_hex(0x7689AC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonCancel, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ButtonCancel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonCancel, lv_color_hex(0x28DCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonCancel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_ButtonCancel);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Cancel");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_SetScreen);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -26);
    lv_obj_set_y(ui_Label8, 30);
    lv_obj_set_align(ui_Label8, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label8, "V");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_SetScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 206);
    lv_obj_set_y(ui_Label2, 31);
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label2, "A");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextAreaUset, ui_event_TextAreaUset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaIset, ui_event_TextAreaIset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetKeyboard, ui_event_SetKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label9, ui_event_Label9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonOk, ui_event_ButtonOk, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonCancel, ui_event_ButtonCancel, LV_EVENT_ALL, NULL);

}
