// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: KORAD_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiSimbolLabel2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_WifiSimbolLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiSimbolLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiSimbolLabel2, 4);
    lv_obj_set_y(ui_WifiSimbolLabel2, 2);
    lv_label_set_text(ui_WifiSimbolLabel2, "W");
    lv_obj_set_style_text_color(ui_WifiSimbolLabel2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiSimbolLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logoLabel2 = lv_label_create(ui_Screen2);
    lv_obj_set_height(ui_logoLabel2, 15);
    lv_obj_set_width(ui_logoLabel2, lv_pct(93));
    lv_obj_set_x(ui_logoLabel2, 12);
    lv_obj_set_y(ui_logoLabel2, 2);
    lv_obj_set_align(ui_logoLabel2, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_logoLabel2, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_logoLabel2, "KORAD");
    lv_obj_clear_flag(ui_logoLabel2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_logoLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_logoLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_logoLabel2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bodyPanel2 = lv_obj_create(ui_Screen2);
    lv_obj_set_height(ui_bodyPanel2, 300);
    lv_obj_set_width(ui_bodyPanel2, lv_pct(100));
    lv_obj_set_x(ui_bodyPanel2, 0);
    lv_obj_set_y(ui_bodyPanel2, 10);
    lv_obj_set_align(ui_bodyPanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_bodyPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bodyPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_bodyPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_bodyPanel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_bodyPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_bodyPanel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_bodyPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uLabel2 = lv_label_create(ui_bodyPanel2);
    lv_obj_set_width(ui_uLabel2, 154);
    lv_obj_set_height(ui_uLabel2, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_uLabel2, 7);
    lv_obj_set_y(ui_uLabel2, 232);
    lv_label_set_text(ui_uLabel2, "88.88");
    lv_obj_add_flag(ui_uLabel2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_letter_space(ui_uLabel2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_uLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_uLabel2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uLabel2, &ui_font_Segment38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iLabel2 = lv_label_create(ui_bodyPanel2);
    lv_obj_set_width(ui_iLabel2, 154);
    lv_obj_set_height(ui_iLabel2, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_iLabel2, 297);
    lv_obj_set_y(ui_iLabel2, 232);
    lv_label_set_text(ui_iLabel2, "88.88");
    lv_obj_add_flag(ui_iLabel2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_letter_space(ui_iLabel2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_iLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_iLabel2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iLabel2, &ui_font_Segment38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ovpLabel2 = lv_label_create(ui_bodyPanel2);
    lv_obj_set_width(ui_ovpLabel2, 60);
    lv_obj_set_height(ui_ovpLabel2, 28);
    lv_obj_set_x(ui_ovpLabel2, 390);
    lv_obj_set_y(ui_ovpLabel2, 10);
    lv_label_set_text(ui_ovpLabel2, "OVP");
    lv_obj_set_style_text_color(ui_ovpLabel2, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ovpLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ovpLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ovpLabel2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ovpLabel2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ovpLabel2, lv_color_hex(0x7C7C7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ovpLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ovpLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ovpLabel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ovpLabel2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ovpLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cvLabel2 = lv_label_create(ui_bodyPanel2);
    lv_obj_set_width(ui_cvLabel2, 60);
    lv_obj_set_height(ui_cvLabel2, 28);
    lv_obj_set_x(ui_cvLabel2, 390);
    lv_obj_set_y(ui_cvLabel2, 50);
    lv_label_set_text(ui_cvLabel2, "CV");
    lv_obj_set_style_text_color(ui_cvLabel2, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cvLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cvLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cvLabel2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cvLabel2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cvLabel2, lv_color_hex(0x7C7C7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cvLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cvLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cvLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cvLabel2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cvLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ocpLabel2 = lv_label_create(ui_bodyPanel2);
    lv_obj_set_width(ui_ocpLabel2, 60);
    lv_obj_set_height(ui_ocpLabel2, 28);
    lv_obj_set_x(ui_ocpLabel2, 390);
    lv_obj_set_y(ui_ocpLabel2, 130);
    lv_label_set_text(ui_ocpLabel2, "OCP");
    lv_obj_set_style_text_color(ui_ocpLabel2, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ocpLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ocpLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ocpLabel2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ocpLabel2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ocpLabel2, lv_color_hex(0x7C7C7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ocpLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ocpLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ocpLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ocpLabel2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ocpLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ccLabel2 = lv_label_create(ui_bodyPanel2);
    lv_obj_set_width(ui_ccLabel2, 60);
    lv_obj_set_height(ui_ccLabel2, 28);
    lv_obj_set_x(ui_ccLabel2, 390);
    lv_obj_set_y(ui_ccLabel2, 170);
    lv_label_set_text(ui_ccLabel2, "CC");
    lv_obj_set_style_text_color(ui_ccLabel2, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ccLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ccLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ccLabel2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ccLabel2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ccLabel2, lv_color_hex(0x7C7C7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ccLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ccLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ccLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ccLabel2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ccLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outLabel2 = lv_label_create(ui_bodyPanel2);
    lv_obj_set_width(ui_outLabel2, 92);
    lv_obj_set_height(ui_outLabel2, 44);
    lv_obj_set_x(ui_outLabel2, 183);
    lv_obj_set_y(ui_outLabel2, 230);
    lv_label_set_text(ui_outLabel2, "OFF");
    lv_obj_set_style_text_align(ui_outLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_outLabel2, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_outLabel2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_outLabel2, lv_color_hex(0x39CB12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_outLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_outLabel2, lv_color_hex(0x929191), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_outLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_outLabel2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_outLabel2, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_outLabel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mLabel2 = lv_label_create(ui_bodyPanel2);
    lv_obj_set_width(ui_mLabel2, 60);
    lv_obj_set_height(ui_mLabel2, 28);
    lv_obj_set_x(ui_mLabel2, 390);
    lv_obj_set_y(ui_mLabel2, 90);
    lv_label_set_text(ui_mLabel2, "MO");
    lv_obj_set_style_text_color(ui_mLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_mLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mLabel2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_mLabel2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mLabel2, lv_color_hex(0x4411A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_mLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_mLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_mLabel2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_mLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wnLabel2 = lv_label_create(ui_bodyPanel2);
    lv_obj_set_width(ui_wnLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wnLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wnLabel2, 16);
    lv_obj_set_y(ui_wnLabel2, 10);
    lv_label_set_text(ui_wnLabel2, "Power, W");
    lv_obj_set_style_text_font(ui_wnLabel2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rnLabel2 = lv_label_create(ui_bodyPanel2);
    lv_obj_set_width(ui_rnLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rnLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rnLabel2, 16);
    lv_obj_set_y(ui_rnLabel2, 50);
    lv_label_set_text(ui_rnLabel2, "Resistance, Om");
    lv_obj_set_style_text_font(ui_rnLabel2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ahnLabel2 = lv_label_create(ui_bodyPanel2);
    lv_obj_set_width(ui_ahnLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ahnLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ahnLabel2, 16);
    lv_obj_set_y(ui_ahnLabel2, 90);
    lv_label_set_text(ui_ahnLabel2, "Energy, A/h");
    lv_obj_set_style_text_font(ui_ahnLabel2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_awnLabel2 = lv_label_create(ui_bodyPanel2);
    lv_obj_set_width(ui_awnLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_awnLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_awnLabel2, 16);
    lv_obj_set_y(ui_awnLabel2, 130);
    lv_label_set_text(ui_awnLabel2, "Energy, W/h");
    lv_obj_set_style_text_font(ui_awnLabel2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tnLabel2 = lv_label_create(ui_bodyPanel2);
    lv_obj_set_width(ui_tnLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tnLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tnLabel2, 19);
    lv_obj_set_y(ui_tnLabel2, 170);
    lv_label_set_text(ui_tnLabel2, "Time, h:m:s");
    lv_obj_set_style_text_font(ui_tnLabel2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pLabel2 = lv_label_create(ui_bodyPanel2);
    lv_obj_set_width(ui_pLabel2, 100);
    lv_obj_set_height(ui_pLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pLabel2, 250);
    lv_obj_set_y(ui_pLabel2, 10);
    lv_label_set_long_mode(ui_pLabel2, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_pLabel2, "888.8");
    lv_obj_set_style_text_align(ui_pLabel2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pLabel2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rLabel2 = lv_label_create(ui_bodyPanel2);
    lv_obj_set_width(ui_rLabel2, 100);
    lv_obj_set_height(ui_rLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rLabel2, 250);
    lv_obj_set_y(ui_rLabel2, 50);
    lv_label_set_long_mode(ui_rLabel2, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_rLabel2, "888.8");
    lv_obj_set_style_text_align(ui_rLabel2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rLabel2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ahLabel2 = lv_label_create(ui_bodyPanel2);
    lv_obj_set_width(ui_ahLabel2, 150);
    lv_obj_set_height(ui_ahLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ahLabel2, 200);
    lv_obj_set_y(ui_ahLabel2, 90);
    lv_label_set_long_mode(ui_ahLabel2, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_ahLabel2, "88888.888");
    lv_obj_set_style_text_align(ui_ahLabel2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ahLabel2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_whLabel2 = lv_label_create(ui_bodyPanel2);
    lv_obj_set_width(ui_whLabel2, 150);
    lv_obj_set_height(ui_whLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_whLabel2, 200);
    lv_obj_set_y(ui_whLabel2, 130);
    lv_label_set_long_mode(ui_whLabel2, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_whLabel2, "888888.88");
    lv_obj_set_style_text_align(ui_whLabel2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_whLabel2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tLabel2 = lv_label_create(ui_bodyPanel2);
    lv_obj_set_width(ui_tLabel2, 150);
    lv_obj_set_height(ui_tLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tLabel2, 200);
    lv_obj_set_y(ui_tLabel2, 170);
    lv_label_set_long_mode(ui_tLabel2, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_tLabel2, "8888:88:88");
    lv_obj_set_style_text_align(ui_tLabel2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tLabel2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_uLabel2, ui_event_uLabel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_iLabel2, ui_event_iLabel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
